// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/migrate"
	"github.com/google/uuid"

	"log/slog"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionrecord"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/task"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ExtractionRecord is the client for interacting with the ExtractionRecord builders.
	ExtractionRecord *ExtractionRecordClient
	// ExtractionSchema is the client for interacting with the ExtractionSchema builders.
	ExtractionSchema *ExtractionSchemaClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ExtractionRecord = NewExtractionRecordClient(c.config)
	c.ExtractionSchema = NewExtractionSchemaClient(c.config)
	c.Task = NewTaskClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
		Logger *slog.Logger
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Logger configures the Logger.
func Logger(v *slog.Logger) Option {
	return func(c *config) {
		c.Logger = v
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		ExtractionRecord: NewExtractionRecordClient(cfg),
		ExtractionSchema: NewExtractionSchemaClient(cfg),
		Task:             NewTaskClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		ExtractionRecord: NewExtractionRecordClient(cfg),
		ExtractionSchema: NewExtractionSchemaClient(cfg),
		Task:             NewTaskClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ExtractionRecord.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ExtractionRecord.Use(hooks...)
	c.ExtractionSchema.Use(hooks...)
	c.Task.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ExtractionRecord.Intercept(interceptors...)
	c.ExtractionSchema.Intercept(interceptors...)
	c.Task.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ExtractionRecordMutation:
		return c.ExtractionRecord.mutate(ctx, m)
	case *ExtractionSchemaMutation:
		return c.ExtractionSchema.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ExtractionRecordClient is a client for the ExtractionRecord schema.
type ExtractionRecordClient struct {
	config
}

// NewExtractionRecordClient returns a client for the ExtractionRecord from the given config.
func NewExtractionRecordClient(c config) *ExtractionRecordClient {
	return &ExtractionRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `extractionrecord.Hooks(f(g(h())))`.
func (c *ExtractionRecordClient) Use(hooks ...Hook) {
	c.hooks.ExtractionRecord = append(c.hooks.ExtractionRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `extractionrecord.Intercept(f(g(h())))`.
func (c *ExtractionRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.ExtractionRecord = append(c.inters.ExtractionRecord, interceptors...)
}

// Create returns a builder for creating a ExtractionRecord entity.
func (c *ExtractionRecordClient) Create() *ExtractionRecordCreate {
	mutation := newExtractionRecordMutation(c.config, OpCreate)
	return &ExtractionRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ExtractionRecord entities.
func (c *ExtractionRecordClient) CreateBulk(builders ...*ExtractionRecordCreate) *ExtractionRecordCreateBulk {
	return &ExtractionRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExtractionRecordClient) MapCreateBulk(slice any, setFunc func(*ExtractionRecordCreate, int)) *ExtractionRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExtractionRecordCreateBulk{err: fmt.Errorf("calling to ExtractionRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExtractionRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExtractionRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ExtractionRecord.
func (c *ExtractionRecordClient) Update() *ExtractionRecordUpdate {
	mutation := newExtractionRecordMutation(c.config, OpUpdate)
	return &ExtractionRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExtractionRecordClient) UpdateOne(_m *ExtractionRecord) *ExtractionRecordUpdateOne {
	mutation := newExtractionRecordMutation(c.config, OpUpdateOne, withExtractionRecord(_m))
	return &ExtractionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExtractionRecordClient) UpdateOneID(id uuid.UUID) *ExtractionRecordUpdateOne {
	mutation := newExtractionRecordMutation(c.config, OpUpdateOne, withExtractionRecordID(id))
	return &ExtractionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ExtractionRecord.
func (c *ExtractionRecordClient) Delete() *ExtractionRecordDelete {
	mutation := newExtractionRecordMutation(c.config, OpDelete)
	return &ExtractionRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExtractionRecordClient) DeleteOne(_m *ExtractionRecord) *ExtractionRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExtractionRecordClient) DeleteOneID(id uuid.UUID) *ExtractionRecordDeleteOne {
	builder := c.Delete().Where(extractionrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExtractionRecordDeleteOne{builder}
}

// Query returns a query builder for ExtractionRecord.
func (c *ExtractionRecordClient) Query() *ExtractionRecordQuery {
	return &ExtractionRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExtractionRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a ExtractionRecord entity by its id.
func (c *ExtractionRecordClient) Get(ctx context.Context, id uuid.UUID) (*ExtractionRecord, error) {
	return c.Query().Where(extractionrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExtractionRecordClient) GetX(ctx context.Context, id uuid.UUID) *ExtractionRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySchema queries the schema edge of a ExtractionRecord.
func (c *ExtractionRecordClient) QuerySchema(_m *ExtractionRecord) *ExtractionSchemaQuery {
	query := (&ExtractionSchemaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(extractionrecord.Table, extractionrecord.FieldID, id),
			sqlgraph.To(extractionschema.Table, extractionschema.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, extractionrecord.SchemaTable, extractionrecord.SchemaColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ExtractionRecordClient) Hooks() []Hook {
	return c.hooks.ExtractionRecord
}

// Interceptors returns the client interceptors.
func (c *ExtractionRecordClient) Interceptors() []Interceptor {
	return c.inters.ExtractionRecord
}

func (c *ExtractionRecordClient) mutate(ctx context.Context, m *ExtractionRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExtractionRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExtractionRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExtractionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExtractionRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ExtractionRecord mutation op: %q", m.Op())
	}
}

// ExtractionSchemaClient is a client for the ExtractionSchema schema.
type ExtractionSchemaClient struct {
	config
}

// NewExtractionSchemaClient returns a client for the ExtractionSchema from the given config.
func NewExtractionSchemaClient(c config) *ExtractionSchemaClient {
	return &ExtractionSchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `extractionschema.Hooks(f(g(h())))`.
func (c *ExtractionSchemaClient) Use(hooks ...Hook) {
	c.hooks.ExtractionSchema = append(c.hooks.ExtractionSchema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `extractionschema.Intercept(f(g(h())))`.
func (c *ExtractionSchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.ExtractionSchema = append(c.inters.ExtractionSchema, interceptors...)
}

// Create returns a builder for creating a ExtractionSchema entity.
func (c *ExtractionSchemaClient) Create() *ExtractionSchemaCreate {
	mutation := newExtractionSchemaMutation(c.config, OpCreate)
	return &ExtractionSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ExtractionSchema entities.
func (c *ExtractionSchemaClient) CreateBulk(builders ...*ExtractionSchemaCreate) *ExtractionSchemaCreateBulk {
	return &ExtractionSchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExtractionSchemaClient) MapCreateBulk(slice any, setFunc func(*ExtractionSchemaCreate, int)) *ExtractionSchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExtractionSchemaCreateBulk{err: fmt.Errorf("calling to ExtractionSchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExtractionSchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExtractionSchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ExtractionSchema.
func (c *ExtractionSchemaClient) Update() *ExtractionSchemaUpdate {
	mutation := newExtractionSchemaMutation(c.config, OpUpdate)
	return &ExtractionSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExtractionSchemaClient) UpdateOne(_m *ExtractionSchema) *ExtractionSchemaUpdateOne {
	mutation := newExtractionSchemaMutation(c.config, OpUpdateOne, withExtractionSchema(_m))
	return &ExtractionSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExtractionSchemaClient) UpdateOneID(id uuid.UUID) *ExtractionSchemaUpdateOne {
	mutation := newExtractionSchemaMutation(c.config, OpUpdateOne, withExtractionSchemaID(id))
	return &ExtractionSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ExtractionSchema.
func (c *ExtractionSchemaClient) Delete() *ExtractionSchemaDelete {
	mutation := newExtractionSchemaMutation(c.config, OpDelete)
	return &ExtractionSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExtractionSchemaClient) DeleteOne(_m *ExtractionSchema) *ExtractionSchemaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExtractionSchemaClient) DeleteOneID(id uuid.UUID) *ExtractionSchemaDeleteOne {
	builder := c.Delete().Where(extractionschema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExtractionSchemaDeleteOne{builder}
}

// Query returns a query builder for ExtractionSchema.
func (c *ExtractionSchemaClient) Query() *ExtractionSchemaQuery {
	return &ExtractionSchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExtractionSchema},
		inters: c.Interceptors(),
	}
}

// Get returns a ExtractionSchema entity by its id.
func (c *ExtractionSchemaClient) Get(ctx context.Context, id uuid.UUID) (*ExtractionSchema, error) {
	return c.Query().Where(extractionschema.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExtractionSchemaClient) GetX(ctx context.Context, id uuid.UUID) *ExtractionSchema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecords queries the records edge of a ExtractionSchema.
func (c *ExtractionSchemaClient) QueryRecords(_m *ExtractionSchema) *ExtractionRecordQuery {
	query := (&ExtractionRecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(extractionschema.Table, extractionschema.FieldID, id),
			sqlgraph.To(extractionrecord.Table, extractionrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, extractionschema.RecordsTable, extractionschema.RecordsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTasks queries the tasks edge of a ExtractionSchema.
func (c *ExtractionSchemaClient) QueryTasks(_m *ExtractionSchema) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(extractionschema.Table, extractionschema.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, extractionschema.TasksTable, extractionschema.TasksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ExtractionSchemaClient) Hooks() []Hook {
	return c.hooks.ExtractionSchema
}

// Interceptors returns the client interceptors.
func (c *ExtractionSchemaClient) Interceptors() []Interceptor {
	return c.inters.ExtractionSchema
}

func (c *ExtractionSchemaClient) mutate(ctx context.Context, m *ExtractionSchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExtractionSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExtractionSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExtractionSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExtractionSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ExtractionSchema mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id uuid.UUID) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id uuid.UUID) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id uuid.UUID) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id uuid.UUID) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySchema queries the schema edge of a Task.
func (c *TaskClient) QuerySchema(_m *Task) *ExtractionSchemaQuery {
	query := (&ExtractionSchemaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(extractionschema.Table, extractionschema.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, task.SchemaTable, task.SchemaColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ExtractionRecord, ExtractionSchema, Task []ent.Hook
	}
	inters struct {
		ExtractionRecord, ExtractionSchema, Task []ent.Interceptor
	}
)
