// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionrecord"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/structpb"
)

// ExtractionRecordCreate is the builder for creating a ExtractionRecord entity.
type ExtractionRecordCreate struct {
	config
	mutation *ExtractionRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRowid sets the "rowid" field.
func (_c *ExtractionRecordCreate) SetRowid(v int64) *ExtractionRecordCreate {
	_c.mutation.SetRowid(v)
	return _c
}

// SetNillableRowid sets the "rowid" field if the given value is not nil.
func (_c *ExtractionRecordCreate) SetNillableRowid(v *int64) *ExtractionRecordCreate {
	if v != nil {
		_c.SetRowid(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ExtractionRecordCreate) SetCreateTime(v time.Time) *ExtractionRecordCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ExtractionRecordCreate) SetNillableCreateTime(v *time.Time) *ExtractionRecordCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ExtractionRecordCreate) SetUpdateTime(v time.Time) *ExtractionRecordCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ExtractionRecordCreate) SetNillableUpdateTime(v *time.Time) *ExtractionRecordCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetValues sets the "values" field.
func (_c *ExtractionRecordCreate) SetValues(v map[string]*structpb.Value) *ExtractionRecordCreate {
	_c.mutation.SetValues(v)
	return _c
}

// SetCaptures sets the "captures" field.
func (_c *ExtractionRecordCreate) SetCaptures(v map[string]*browserv1beta.ElementCapture) *ExtractionRecordCreate {
	_c.mutation.SetCaptures(v)
	return _c
}

// SetSchemaID sets the "schema_id" field.
func (_c *ExtractionRecordCreate) SetSchemaID(v uuid.UUID) *ExtractionRecordCreate {
	_c.mutation.SetSchemaID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *ExtractionRecordCreate) SetTaskID(v uuid.UUID) *ExtractionRecordCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetExtensionID sets the "extension_id" field.
func (_c *ExtractionRecordCreate) SetExtensionID(v string) *ExtractionRecordCreate {
	_c.mutation.SetExtensionID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ExtractionRecordCreate) SetID(v uuid.UUID) *ExtractionRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExtractionRecordCreate) SetNillableID(v *uuid.UUID) *ExtractionRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSchema sets the "schema" edge to the ExtractionSchema entity.
func (_c *ExtractionRecordCreate) SetSchema(v *ExtractionSchema) *ExtractionRecordCreate {
	return _c.SetSchemaID(v.ID)
}

// Mutation returns the ExtractionRecordMutation object of the builder.
func (_c *ExtractionRecordCreate) Mutation() *ExtractionRecordMutation {
	return _c.mutation
}

// Save creates the ExtractionRecord in the database.
func (_c *ExtractionRecordCreate) Save(ctx context.Context) (*ExtractionRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExtractionRecordCreate) SaveX(ctx context.Context) *ExtractionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtractionRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtractionRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExtractionRecordCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := extractionrecord.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := extractionrecord.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := extractionrecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExtractionRecordCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "ExtractionRecord.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "ExtractionRecord.update_time"`)}
	}
	if _, ok := _c.mutation.Values(); !ok {
		return &ValidationError{Name: "values", err: errors.New(`ent: missing required field "ExtractionRecord.values"`)}
	}
	if _, ok := _c.mutation.Captures(); !ok {
		return &ValidationError{Name: "captures", err: errors.New(`ent: missing required field "ExtractionRecord.captures"`)}
	}
	if _, ok := _c.mutation.SchemaID(); !ok {
		return &ValidationError{Name: "schema_id", err: errors.New(`ent: missing required field "ExtractionRecord.schema_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "ExtractionRecord.task_id"`)}
	}
	if _, ok := _c.mutation.ExtensionID(); !ok {
		return &ValidationError{Name: "extension_id", err: errors.New(`ent: missing required field "ExtractionRecord.extension_id"`)}
	}
	if len(_c.mutation.SchemaIDs()) == 0 {
		return &ValidationError{Name: "schema", err: errors.New(`ent: missing required edge "ExtractionRecord.schema"`)}
	}
	return nil
}

func (_c *ExtractionRecordCreate) sqlSave(ctx context.Context) (*ExtractionRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExtractionRecordCreate) createSpec() (*ExtractionRecord, *sqlgraph.CreateSpec, error) {
	var (
		_node = &ExtractionRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(extractionrecord.Table, sqlgraph.NewFieldSpec(extractionrecord.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Rowid(); ok {
		_spec.SetField(extractionrecord.FieldRowid, field.TypeInt64, value)
		_node.Rowid = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(extractionrecord.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(extractionrecord.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Values(); ok {
		vv, err := extractionrecord.ValueScanner.Values.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(extractionrecord.FieldValues, field.TypeBytes, vv)
		_node.Values = value
	}
	if value, ok := _c.mutation.Captures(); ok {
		vv, err := extractionrecord.ValueScanner.Captures.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(extractionrecord.FieldCaptures, field.TypeBytes, vv)
		_node.Captures = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(extractionrecord.FieldTaskID, field.TypeUUID, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.ExtensionID(); ok {
		_spec.SetField(extractionrecord.FieldExtensionID, field.TypeString, value)
		_node.ExtensionID = value
	}
	if nodes := _c.mutation.SchemaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extractionrecord.SchemaTable,
			Columns: []string{extractionrecord.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SchemaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtractionRecord.Create().
//		SetRowid(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtractionRecordUpsert) {
//			SetRowid(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtractionRecordCreate) OnConflict(opts ...sql.ConflictOption) *ExtractionRecordUpsertOne {
	_c.conflict = opts
	return &ExtractionRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtractionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtractionRecordCreate) OnConflictColumns(columns ...string) *ExtractionRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtractionRecordUpsertOne{
		create: _c,
	}
}

type (
	// ExtractionRecordUpsertOne is the builder for "upsert"-ing
	//  one ExtractionRecord node.
	ExtractionRecordUpsertOne struct {
		create *ExtractionRecordCreate
	}

	// ExtractionRecordUpsert is the "OnConflict" setter.
	ExtractionRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *ExtractionRecordUpsert) SetUpdateTime(v time.Time) *ExtractionRecordUpsert {
	u.Set(extractionrecord.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExtractionRecordUpsert) UpdateUpdateTime() *ExtractionRecordUpsert {
	u.SetExcluded(extractionrecord.FieldUpdateTime)
	return u
}

// SetValues sets the "values" field.
func (u *ExtractionRecordUpsert) SetValues(v map[string]*structpb.Value) *ExtractionRecordUpsert {
	u.Set(extractionrecord.FieldValues, v)
	return u
}

// UpdateValues sets the "values" field to the value that was provided on create.
func (u *ExtractionRecordUpsert) UpdateValues() *ExtractionRecordUpsert {
	u.SetExcluded(extractionrecord.FieldValues)
	return u
}

// SetCaptures sets the "captures" field.
func (u *ExtractionRecordUpsert) SetCaptures(v map[string]*browserv1beta.ElementCapture) *ExtractionRecordUpsert {
	u.Set(extractionrecord.FieldCaptures, v)
	return u
}

// UpdateCaptures sets the "captures" field to the value that was provided on create.
func (u *ExtractionRecordUpsert) UpdateCaptures() *ExtractionRecordUpsert {
	u.SetExcluded(extractionrecord.FieldCaptures)
	return u
}

// SetSchemaID sets the "schema_id" field.
func (u *ExtractionRecordUpsert) SetSchemaID(v uuid.UUID) *ExtractionRecordUpsert {
	u.Set(extractionrecord.FieldSchemaID, v)
	return u
}

// UpdateSchemaID sets the "schema_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsert) UpdateSchemaID() *ExtractionRecordUpsert {
	u.SetExcluded(extractionrecord.FieldSchemaID)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *ExtractionRecordUpsert) SetTaskID(v uuid.UUID) *ExtractionRecordUpsert {
	u.Set(extractionrecord.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsert) UpdateTaskID() *ExtractionRecordUpsert {
	u.SetExcluded(extractionrecord.FieldTaskID)
	return u
}

// SetExtensionID sets the "extension_id" field.
func (u *ExtractionRecordUpsert) SetExtensionID(v string) *ExtractionRecordUpsert {
	u.Set(extractionrecord.FieldExtensionID, v)
	return u
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsert) UpdateExtensionID() *ExtractionRecordUpsert {
	u.SetExcluded(extractionrecord.FieldExtensionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExtractionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(extractionrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExtractionRecordUpsertOne) UpdateNewValues() *ExtractionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(extractionrecord.FieldID)
		}
		if _, exists := u.create.mutation.Rowid(); exists {
			s.SetIgnore(extractionrecord.FieldRowid)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(extractionrecord.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtractionRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExtractionRecordUpsertOne) Ignore() *ExtractionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtractionRecordUpsertOne) DoNothing() *ExtractionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtractionRecordCreate.OnConflict
// documentation for more info.
func (u *ExtractionRecordUpsertOne) Update(set func(*ExtractionRecordUpsert)) *ExtractionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtractionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ExtractionRecordUpsertOne) SetUpdateTime(v time.Time) *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExtractionRecordUpsertOne) UpdateUpdateTime() *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetValues sets the "values" field.
func (u *ExtractionRecordUpsertOne) SetValues(v map[string]*structpb.Value) *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetValues(v)
	})
}

// UpdateValues sets the "values" field to the value that was provided on create.
func (u *ExtractionRecordUpsertOne) UpdateValues() *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateValues()
	})
}

// SetCaptures sets the "captures" field.
func (u *ExtractionRecordUpsertOne) SetCaptures(v map[string]*browserv1beta.ElementCapture) *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetCaptures(v)
	})
}

// UpdateCaptures sets the "captures" field to the value that was provided on create.
func (u *ExtractionRecordUpsertOne) UpdateCaptures() *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateCaptures()
	})
}

// SetSchemaID sets the "schema_id" field.
func (u *ExtractionRecordUpsertOne) SetSchemaID(v uuid.UUID) *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetSchemaID(v)
	})
}

// UpdateSchemaID sets the "schema_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsertOne) UpdateSchemaID() *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateSchemaID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *ExtractionRecordUpsertOne) SetTaskID(v uuid.UUID) *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsertOne) UpdateTaskID() *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateTaskID()
	})
}

// SetExtensionID sets the "extension_id" field.
func (u *ExtractionRecordUpsertOne) SetExtensionID(v string) *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetExtensionID(v)
	})
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsertOne) UpdateExtensionID() *ExtractionRecordUpsertOne {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateExtensionID()
	})
}

// Exec executes the query.
func (u *ExtractionRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtractionRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtractionRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExtractionRecordUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ExtractionRecordUpsertOne.ID is not supported by MySQL driver. Use ExtractionRecordUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExtractionRecordUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExtractionRecordCreateBulk is the builder for creating many ExtractionRecord entities in bulk.
type ExtractionRecordCreateBulk struct {
	config
	err      error
	builders []*ExtractionRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the ExtractionRecord entities in the database.
func (_c *ExtractionRecordCreateBulk) Save(ctx context.Context) ([]*ExtractionRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExtractionRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExtractionRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExtractionRecordCreateBulk) SaveX(ctx context.Context) []*ExtractionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtractionRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtractionRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtractionRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtractionRecordUpsert) {
//			SetRowid(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtractionRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExtractionRecordUpsertBulk {
	_c.conflict = opts
	return &ExtractionRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtractionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtractionRecordCreateBulk) OnConflictColumns(columns ...string) *ExtractionRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtractionRecordUpsertBulk{
		create: _c,
	}
}

// ExtractionRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of ExtractionRecord nodes.
type ExtractionRecordUpsertBulk struct {
	create *ExtractionRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExtractionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(extractionrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExtractionRecordUpsertBulk) UpdateNewValues() *ExtractionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(extractionrecord.FieldID)
			}
			if _, exists := b.mutation.Rowid(); exists {
				s.SetIgnore(extractionrecord.FieldRowid)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(extractionrecord.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtractionRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExtractionRecordUpsertBulk) Ignore() *ExtractionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtractionRecordUpsertBulk) DoNothing() *ExtractionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtractionRecordCreateBulk.OnConflict
// documentation for more info.
func (u *ExtractionRecordUpsertBulk) Update(set func(*ExtractionRecordUpsert)) *ExtractionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtractionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ExtractionRecordUpsertBulk) SetUpdateTime(v time.Time) *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExtractionRecordUpsertBulk) UpdateUpdateTime() *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetValues sets the "values" field.
func (u *ExtractionRecordUpsertBulk) SetValues(v map[string]*structpb.Value) *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetValues(v)
	})
}

// UpdateValues sets the "values" field to the value that was provided on create.
func (u *ExtractionRecordUpsertBulk) UpdateValues() *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateValues()
	})
}

// SetCaptures sets the "captures" field.
func (u *ExtractionRecordUpsertBulk) SetCaptures(v map[string]*browserv1beta.ElementCapture) *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetCaptures(v)
	})
}

// UpdateCaptures sets the "captures" field to the value that was provided on create.
func (u *ExtractionRecordUpsertBulk) UpdateCaptures() *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateCaptures()
	})
}

// SetSchemaID sets the "schema_id" field.
func (u *ExtractionRecordUpsertBulk) SetSchemaID(v uuid.UUID) *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetSchemaID(v)
	})
}

// UpdateSchemaID sets the "schema_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsertBulk) UpdateSchemaID() *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateSchemaID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *ExtractionRecordUpsertBulk) SetTaskID(v uuid.UUID) *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsertBulk) UpdateTaskID() *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateTaskID()
	})
}

// SetExtensionID sets the "extension_id" field.
func (u *ExtractionRecordUpsertBulk) SetExtensionID(v string) *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.SetExtensionID(v)
	})
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *ExtractionRecordUpsertBulk) UpdateExtensionID() *ExtractionRecordUpsertBulk {
	return u.Update(func(s *ExtractionRecordUpsert) {
		s.UpdateExtensionID()
	})
}

// Exec executes the query.
func (u *ExtractionRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExtractionRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtractionRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtractionRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
