// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionrecord"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/task"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
)

// ExtractionSchemaCreate is the builder for creating a ExtractionSchema entity.
type ExtractionSchemaCreate struct {
	config
	mutation *ExtractionSchemaMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRowid sets the "rowid" field.
func (_c *ExtractionSchemaCreate) SetRowid(v int64) *ExtractionSchemaCreate {
	_c.mutation.SetRowid(v)
	return _c
}

// SetNillableRowid sets the "rowid" field if the given value is not nil.
func (_c *ExtractionSchemaCreate) SetNillableRowid(v *int64) *ExtractionSchemaCreate {
	if v != nil {
		_c.SetRowid(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ExtractionSchemaCreate) SetCreateTime(v time.Time) *ExtractionSchemaCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ExtractionSchemaCreate) SetNillableCreateTime(v *time.Time) *ExtractionSchemaCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ExtractionSchemaCreate) SetUpdateTime(v time.Time) *ExtractionSchemaCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ExtractionSchemaCreate) SetNillableUpdateTime(v *time.Time) *ExtractionSchemaCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ExtractionSchemaCreate) SetName(v string) *ExtractionSchemaCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExtractionSchemaCreate) SetDescription(v string) *ExtractionSchemaCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ExtractionSchemaCreate) SetNillableDescription(v *string) *ExtractionSchemaCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetFields sets the "fields" field.
func (_c *ExtractionSchemaCreate) SetFields(v []*browserv1beta.FieldDef) *ExtractionSchemaCreate {
	_c.mutation.SetFields(v)
	return _c
}

// SetExtensionID sets the "extension_id" field.
func (_c *ExtractionSchemaCreate) SetExtensionID(v string) *ExtractionSchemaCreate {
	_c.mutation.SetExtensionID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ExtractionSchemaCreate) SetID(v uuid.UUID) *ExtractionSchemaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExtractionSchemaCreate) SetNillableID(v *uuid.UUID) *ExtractionSchemaCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddRecordIDs adds the "records" edge to the ExtractionRecord entity by IDs.
func (_c *ExtractionSchemaCreate) AddRecordIDs(ids ...uuid.UUID) *ExtractionSchemaCreate {
	_c.mutation.AddRecordIDs(ids...)
	return _c
}

// AddRecords adds the "records" edges to the ExtractionRecord entity.
func (_c *ExtractionSchemaCreate) AddRecords(v ...*ExtractionRecord) *ExtractionSchemaCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *ExtractionSchemaCreate) AddTaskIDs(ids ...uuid.UUID) *ExtractionSchemaCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *ExtractionSchemaCreate) AddTasks(v ...*Task) *ExtractionSchemaCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the ExtractionSchemaMutation object of the builder.
func (_c *ExtractionSchemaCreate) Mutation() *ExtractionSchemaMutation {
	return _c.mutation
}

// Save creates the ExtractionSchema in the database.
func (_c *ExtractionSchemaCreate) Save(ctx context.Context) (*ExtractionSchema, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExtractionSchemaCreate) SaveX(ctx context.Context) *ExtractionSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtractionSchemaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtractionSchemaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExtractionSchemaCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := extractionschema.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := extractionschema.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := extractionschema.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExtractionSchemaCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "ExtractionSchema.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "ExtractionSchema.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ExtractionSchema.name"`)}
	}
	if _, ok := _c.mutation.GetFields(); !ok {
		return &ValidationError{Name: "fields", err: errors.New(`ent: missing required field "ExtractionSchema.fields"`)}
	}
	if _, ok := _c.mutation.ExtensionID(); !ok {
		return &ValidationError{Name: "extension_id", err: errors.New(`ent: missing required field "ExtractionSchema.extension_id"`)}
	}
	return nil
}

func (_c *ExtractionSchemaCreate) sqlSave(ctx context.Context) (*ExtractionSchema, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExtractionSchemaCreate) createSpec() (*ExtractionSchema, *sqlgraph.CreateSpec, error) {
	var (
		_node = &ExtractionSchema{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(extractionschema.Table, sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Rowid(); ok {
		_spec.SetField(extractionschema.FieldRowid, field.TypeInt64, value)
		_node.Rowid = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(extractionschema.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(extractionschema.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(extractionschema.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(extractionschema.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.GetFields(); ok {
		vv, err := extractionschema.ValueScanner.Fields.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(extractionschema.FieldFields, field.TypeBytes, vv)
		_node.Fields = value
	}
	if value, ok := _c.mutation.ExtensionID(); ok {
		_spec.SetField(extractionschema.FieldExtensionID, field.TypeString, value)
		_node.ExtensionID = value
	}
	if nodes := _c.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   extractionschema.RecordsTable,
			Columns: []string{extractionschema.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionrecord.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   extractionschema.TasksTable,
			Columns: []string{extractionschema.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtractionSchema.Create().
//		SetRowid(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtractionSchemaUpsert) {
//			SetRowid(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtractionSchemaCreate) OnConflict(opts ...sql.ConflictOption) *ExtractionSchemaUpsertOne {
	_c.conflict = opts
	return &ExtractionSchemaUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtractionSchema.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtractionSchemaCreate) OnConflictColumns(columns ...string) *ExtractionSchemaUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtractionSchemaUpsertOne{
		create: _c,
	}
}

type (
	// ExtractionSchemaUpsertOne is the builder for "upsert"-ing
	//  one ExtractionSchema node.
	ExtractionSchemaUpsertOne struct {
		create *ExtractionSchemaCreate
	}

	// ExtractionSchemaUpsert is the "OnConflict" setter.
	ExtractionSchemaUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *ExtractionSchemaUpsert) SetUpdateTime(v time.Time) *ExtractionSchemaUpsert {
	u.Set(extractionschema.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExtractionSchemaUpsert) UpdateUpdateTime() *ExtractionSchemaUpsert {
	u.SetExcluded(extractionschema.FieldUpdateTime)
	return u
}

// SetName sets the "name" field.
func (u *ExtractionSchemaUpsert) SetName(v string) *ExtractionSchemaUpsert {
	u.Set(extractionschema.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExtractionSchemaUpsert) UpdateName() *ExtractionSchemaUpsert {
	u.SetExcluded(extractionschema.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ExtractionSchemaUpsert) SetDescription(v string) *ExtractionSchemaUpsert {
	u.Set(extractionschema.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ExtractionSchemaUpsert) UpdateDescription() *ExtractionSchemaUpsert {
	u.SetExcluded(extractionschema.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ExtractionSchemaUpsert) ClearDescription() *ExtractionSchemaUpsert {
	u.SetNull(extractionschema.FieldDescription)
	return u
}

// SetFields sets the "fields" field.
func (u *ExtractionSchemaUpsert) SetFields(v []*browserv1beta.FieldDef) *ExtractionSchemaUpsert {
	u.Set(extractionschema.FieldFields, v)
	return u
}

// UpdateFields sets the "fields" field to the value that was provided on create.
func (u *ExtractionSchemaUpsert) UpdateFields() *ExtractionSchemaUpsert {
	u.SetExcluded(extractionschema.FieldFields)
	return u
}

// SetExtensionID sets the "extension_id" field.
func (u *ExtractionSchemaUpsert) SetExtensionID(v string) *ExtractionSchemaUpsert {
	u.Set(extractionschema.FieldExtensionID, v)
	return u
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *ExtractionSchemaUpsert) UpdateExtensionID() *ExtractionSchemaUpsert {
	u.SetExcluded(extractionschema.FieldExtensionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExtractionSchema.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(extractionschema.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExtractionSchemaUpsertOne) UpdateNewValues() *ExtractionSchemaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(extractionschema.FieldID)
		}
		if _, exists := u.create.mutation.Rowid(); exists {
			s.SetIgnore(extractionschema.FieldRowid)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(extractionschema.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtractionSchema.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExtractionSchemaUpsertOne) Ignore() *ExtractionSchemaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtractionSchemaUpsertOne) DoNothing() *ExtractionSchemaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtractionSchemaCreate.OnConflict
// documentation for more info.
func (u *ExtractionSchemaUpsertOne) Update(set func(*ExtractionSchemaUpsert)) *ExtractionSchemaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtractionSchemaUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ExtractionSchemaUpsertOne) SetUpdateTime(v time.Time) *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertOne) UpdateUpdateTime() *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetName sets the "name" field.
func (u *ExtractionSchemaUpsertOne) SetName(v string) *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertOne) UpdateName() *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ExtractionSchemaUpsertOne) SetDescription(v string) *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertOne) UpdateDescription() *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ExtractionSchemaUpsertOne) ClearDescription() *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.ClearDescription()
	})
}

// SetFields sets the "fields" field.
func (u *ExtractionSchemaUpsertOne) SetFields(v []*browserv1beta.FieldDef) *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetFields(v)
	})
}

// UpdateFields sets the "fields" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertOne) UpdateFields() *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateFields()
	})
}

// SetExtensionID sets the "extension_id" field.
func (u *ExtractionSchemaUpsertOne) SetExtensionID(v string) *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetExtensionID(v)
	})
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertOne) UpdateExtensionID() *ExtractionSchemaUpsertOne {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateExtensionID()
	})
}

// Exec executes the query.
func (u *ExtractionSchemaUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtractionSchemaCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtractionSchemaUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExtractionSchemaUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ExtractionSchemaUpsertOne.ID is not supported by MySQL driver. Use ExtractionSchemaUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExtractionSchemaUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExtractionSchemaCreateBulk is the builder for creating many ExtractionSchema entities in bulk.
type ExtractionSchemaCreateBulk struct {
	config
	err      error
	builders []*ExtractionSchemaCreate
	conflict []sql.ConflictOption
}

// Save creates the ExtractionSchema entities in the database.
func (_c *ExtractionSchemaCreateBulk) Save(ctx context.Context) ([]*ExtractionSchema, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExtractionSchema, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExtractionSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExtractionSchemaCreateBulk) SaveX(ctx context.Context) []*ExtractionSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtractionSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtractionSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtractionSchema.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtractionSchemaUpsert) {
//			SetRowid(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtractionSchemaCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExtractionSchemaUpsertBulk {
	_c.conflict = opts
	return &ExtractionSchemaUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtractionSchema.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtractionSchemaCreateBulk) OnConflictColumns(columns ...string) *ExtractionSchemaUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtractionSchemaUpsertBulk{
		create: _c,
	}
}

// ExtractionSchemaUpsertBulk is the builder for "upsert"-ing
// a bulk of ExtractionSchema nodes.
type ExtractionSchemaUpsertBulk struct {
	create *ExtractionSchemaCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExtractionSchema.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(extractionschema.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExtractionSchemaUpsertBulk) UpdateNewValues() *ExtractionSchemaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(extractionschema.FieldID)
			}
			if _, exists := b.mutation.Rowid(); exists {
				s.SetIgnore(extractionschema.FieldRowid)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(extractionschema.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtractionSchema.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExtractionSchemaUpsertBulk) Ignore() *ExtractionSchemaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtractionSchemaUpsertBulk) DoNothing() *ExtractionSchemaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtractionSchemaCreateBulk.OnConflict
// documentation for more info.
func (u *ExtractionSchemaUpsertBulk) Update(set func(*ExtractionSchemaUpsert)) *ExtractionSchemaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtractionSchemaUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ExtractionSchemaUpsertBulk) SetUpdateTime(v time.Time) *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertBulk) UpdateUpdateTime() *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetName sets the "name" field.
func (u *ExtractionSchemaUpsertBulk) SetName(v string) *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertBulk) UpdateName() *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ExtractionSchemaUpsertBulk) SetDescription(v string) *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertBulk) UpdateDescription() *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ExtractionSchemaUpsertBulk) ClearDescription() *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.ClearDescription()
	})
}

// SetFields sets the "fields" field.
func (u *ExtractionSchemaUpsertBulk) SetFields(v []*browserv1beta.FieldDef) *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetFields(v)
	})
}

// UpdateFields sets the "fields" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertBulk) UpdateFields() *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateFields()
	})
}

// SetExtensionID sets the "extension_id" field.
func (u *ExtractionSchemaUpsertBulk) SetExtensionID(v string) *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.SetExtensionID(v)
	})
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *ExtractionSchemaUpsertBulk) UpdateExtensionID() *ExtractionSchemaUpsertBulk {
	return u.Update(func(s *ExtractionSchemaUpsert) {
		s.UpdateExtensionID()
	})
}

// Exec executes the query.
func (u *ExtractionSchemaUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExtractionSchemaCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtractionSchemaCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtractionSchemaUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
