// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
)

// ExtractionSchema is the model entity for the ExtractionSchema schema.
type ExtractionSchema struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Rowid holds the value of the "rowid" field.
	Rowid int64 `json:"rowid,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Fields holds the value of the "fields" field.
	Fields []*browserv1beta.FieldDef `json:"fields,omitempty"`
	// ExtensionID holds the value of the "extension_id" field.
	ExtensionID string `json:"extension_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExtractionSchemaQuery when eager-loading is set.
	Edges        ExtractionSchemaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExtractionSchemaEdges holds the relations/edges for other nodes in the graph.
type ExtractionSchemaEdges struct {
	// Records holds the value of the records edge.
	Records []*ExtractionRecord `json:"records,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RecordsOrErr returns the Records value or an error if the edge
// was not loaded in eager-loading.
func (e ExtractionSchemaEdges) RecordsOrErr() ([]*ExtractionRecord, error) {
	if e.loadedTypes[0] {
		return e.Records, nil
	}
	return nil, &NotLoadedError{edge: "records"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e ExtractionSchemaEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExtractionSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case extractionschema.FieldRowid:
			values[i] = new(sql.NullInt64)
		case extractionschema.FieldName, extractionschema.FieldDescription, extractionschema.FieldExtensionID:
			values[i] = new(sql.NullString)
		case extractionschema.FieldCreateTime, extractionschema.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case extractionschema.FieldID:
			values[i] = new(uuid.UUID)
		case extractionschema.FieldFields:
			values[i] = extractionschema.ValueScanner.Fields.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExtractionSchema fields.
func (_m *ExtractionSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case extractionschema.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case extractionschema.FieldRowid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rowid", values[i])
			} else if value.Valid {
				_m.Rowid = value.Int64
			}
		case extractionschema.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case extractionschema.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case extractionschema.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case extractionschema.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case extractionschema.FieldFields:
			if value, err := extractionschema.ValueScanner.Fields.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.Fields = value
			}
		case extractionschema.FieldExtensionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extension_id", values[i])
			} else if value.Valid {
				_m.ExtensionID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExtractionSchema.
// This includes values selected through modifiers, order, etc.
func (_m *ExtractionSchema) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecords queries the "records" edge of the ExtractionSchema entity.
func (_m *ExtractionSchema) QueryRecords() *ExtractionRecordQuery {
	return NewExtractionSchemaClient(_m.config).QueryRecords(_m)
}

// QueryTasks queries the "tasks" edge of the ExtractionSchema entity.
func (_m *ExtractionSchema) QueryTasks() *TaskQuery {
	return NewExtractionSchemaClient(_m.config).QueryTasks(_m)
}

// Update returns a builder for updating this ExtractionSchema.
// Note that you need to call ExtractionSchema.Unwrap() before calling this method if this ExtractionSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExtractionSchema) Update() *ExtractionSchemaUpdateOne {
	return NewExtractionSchemaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExtractionSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExtractionSchema) Unwrap() *ExtractionSchema {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExtractionSchema is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExtractionSchema) String() string {
	var builder strings.Builder
	builder.WriteString("ExtractionSchema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rowid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rowid))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.Fields))
	builder.WriteString(", ")
	builder.WriteString("extension_id=")
	builder.WriteString(_m.ExtensionID)
	builder.WriteByte(')')
	return builder.String()
}

// ExtractionSchemas is a parsable slice of ExtractionSchema.
type ExtractionSchemas []*ExtractionSchema
