// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionrecord"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/structpb"
)

// ExtractionRecord is the model entity for the ExtractionRecord schema.
type ExtractionRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Rowid holds the value of the "rowid" field.
	Rowid int64 `json:"rowid,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Values holds the value of the "values" field.
	Values map[string]*structpb.Value `json:"values,omitempty"`
	// Captures holds the value of the "captures" field.
	Captures map[string]*browserv1beta.ElementCapture `json:"captures,omitempty"`
	// SchemaID holds the value of the "schema_id" field.
	SchemaID uuid.UUID `json:"schema_id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// ExtensionID holds the value of the "extension_id" field.
	ExtensionID string `json:"extension_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExtractionRecordQuery when eager-loading is set.
	Edges        ExtractionRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExtractionRecordEdges holds the relations/edges for other nodes in the graph.
type ExtractionRecordEdges struct {
	// Schema holds the value of the schema edge.
	Schema *ExtractionSchema `json:"schema,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SchemaOrErr returns the Schema value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExtractionRecordEdges) SchemaOrErr() (*ExtractionSchema, error) {
	if e.Schema != nil {
		return e.Schema, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: extractionschema.Label}
	}
	return nil, &NotLoadedError{edge: "schema"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExtractionRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case extractionrecord.FieldRowid:
			values[i] = new(sql.NullInt64)
		case extractionrecord.FieldExtensionID:
			values[i] = new(sql.NullString)
		case extractionrecord.FieldCreateTime, extractionrecord.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case extractionrecord.FieldID, extractionrecord.FieldSchemaID, extractionrecord.FieldTaskID:
			values[i] = new(uuid.UUID)
		case extractionrecord.FieldValues:
			values[i] = extractionrecord.ValueScanner.Values.ScanValue()
		case extractionrecord.FieldCaptures:
			values[i] = extractionrecord.ValueScanner.Captures.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExtractionRecord fields.
func (_m *ExtractionRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case extractionrecord.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case extractionrecord.FieldRowid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rowid", values[i])
			} else if value.Valid {
				_m.Rowid = value.Int64
			}
		case extractionrecord.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case extractionrecord.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case extractionrecord.FieldValues:
			if value, err := extractionrecord.ValueScanner.Values.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.Values = value
			}
		case extractionrecord.FieldCaptures:
			if value, err := extractionrecord.ValueScanner.Captures.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.Captures = value
			}
		case extractionrecord.FieldSchemaID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field schema_id", values[i])
			} else if value != nil {
				_m.SchemaID = *value
			}
		case extractionrecord.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case extractionrecord.FieldExtensionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extension_id", values[i])
			} else if value.Valid {
				_m.ExtensionID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExtractionRecord.
// This includes values selected through modifiers, order, etc.
func (_m *ExtractionRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySchema queries the "schema" edge of the ExtractionRecord entity.
func (_m *ExtractionRecord) QuerySchema() *ExtractionSchemaQuery {
	return NewExtractionRecordClient(_m.config).QuerySchema(_m)
}

// Update returns a builder for updating this ExtractionRecord.
// Note that you need to call ExtractionRecord.Unwrap() before calling this method if this ExtractionRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExtractionRecord) Update() *ExtractionRecordUpdateOne {
	return NewExtractionRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExtractionRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExtractionRecord) Unwrap() *ExtractionRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExtractionRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExtractionRecord) String() string {
	var builder strings.Builder
	builder.WriteString("ExtractionRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rowid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rowid))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("values=")
	builder.WriteString(fmt.Sprintf("%v", _m.Values))
	builder.WriteString(", ")
	builder.WriteString("captures=")
	builder.WriteString(fmt.Sprintf("%v", _m.Captures))
	builder.WriteString(", ")
	builder.WriteString("schema_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SchemaID))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("extension_id=")
	builder.WriteString(_m.ExtensionID)
	builder.WriteByte(')')
	return builder.String()
}

// ExtractionRecords is a parsable slice of ExtractionRecord.
type ExtractionRecords []*ExtractionRecord
