// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionrecord"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/predicate"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/structpb"
)

// ExtractionRecordUpdate is the builder for updating ExtractionRecord entities.
type ExtractionRecordUpdate struct {
	config
	hooks    []Hook
	mutation *ExtractionRecordMutation
}

// Where appends a list predicates to the ExtractionRecordUpdate builder.
func (_u *ExtractionRecordUpdate) Where(ps ...predicate.ExtractionRecord) *ExtractionRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ExtractionRecordUpdate) SetUpdateTime(v time.Time) *ExtractionRecordUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetValues sets the "values" field.
func (_u *ExtractionRecordUpdate) SetValues(v map[string]*structpb.Value) *ExtractionRecordUpdate {
	_u.mutation.SetValues(v)
	return _u
}

// SetCaptures sets the "captures" field.
func (_u *ExtractionRecordUpdate) SetCaptures(v map[string]*browserv1beta.ElementCapture) *ExtractionRecordUpdate {
	_u.mutation.SetCaptures(v)
	return _u
}

// SetSchemaID sets the "schema_id" field.
func (_u *ExtractionRecordUpdate) SetSchemaID(v uuid.UUID) *ExtractionRecordUpdate {
	_u.mutation.SetSchemaID(v)
	return _u
}

// SetNillableSchemaID sets the "schema_id" field if the given value is not nil.
func (_u *ExtractionRecordUpdate) SetNillableSchemaID(v *uuid.UUID) *ExtractionRecordUpdate {
	if v != nil {
		_u.SetSchemaID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *ExtractionRecordUpdate) SetTaskID(v uuid.UUID) *ExtractionRecordUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *ExtractionRecordUpdate) SetNillableTaskID(v *uuid.UUID) *ExtractionRecordUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetExtensionID sets the "extension_id" field.
func (_u *ExtractionRecordUpdate) SetExtensionID(v string) *ExtractionRecordUpdate {
	_u.mutation.SetExtensionID(v)
	return _u
}

// SetNillableExtensionID sets the "extension_id" field if the given value is not nil.
func (_u *ExtractionRecordUpdate) SetNillableExtensionID(v *string) *ExtractionRecordUpdate {
	if v != nil {
		_u.SetExtensionID(*v)
	}
	return _u
}

// SetSchema sets the "schema" edge to the ExtractionSchema entity.
func (_u *ExtractionRecordUpdate) SetSchema(v *ExtractionSchema) *ExtractionRecordUpdate {
	return _u.SetSchemaID(v.ID)
}

// Mutation returns the ExtractionRecordMutation object of the builder.
func (_u *ExtractionRecordUpdate) Mutation() *ExtractionRecordMutation {
	return _u.mutation
}

// ClearSchema clears the "schema" edge to the ExtractionSchema entity.
func (_u *ExtractionRecordUpdate) ClearSchema() *ExtractionRecordUpdate {
	_u.mutation.ClearSchema()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExtractionRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExtractionRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExtractionRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExtractionRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExtractionRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := extractionrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExtractionRecordUpdate) check() error {
	if _u.mutation.SchemaCleared() && len(_u.mutation.SchemaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExtractionRecord.schema"`)
	}
	return nil
}

func (_u *ExtractionRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(extractionrecord.Table, extractionrecord.Columns, sqlgraph.NewFieldSpec(extractionrecord.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RowidCleared() {
		_spec.ClearField(extractionrecord.FieldRowid, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(extractionrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Values(); ok {
		vv, err := extractionrecord.ValueScanner.Values.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(extractionrecord.FieldValues, field.TypeBytes, vv)
	}
	if value, ok := _u.mutation.Captures(); ok {
		vv, err := extractionrecord.ValueScanner.Captures.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(extractionrecord.FieldCaptures, field.TypeBytes, vv)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(extractionrecord.FieldTaskID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExtensionID(); ok {
		_spec.SetField(extractionrecord.FieldExtensionID, field.TypeString, value)
	}
	if _u.mutation.SchemaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extractionrecord.SchemaTable,
			Columns: []string{extractionrecord.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchemaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extractionrecord.SchemaTable,
			Columns: []string{extractionrecord.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{extractionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExtractionRecordUpdateOne is the builder for updating a single ExtractionRecord entity.
type ExtractionRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExtractionRecordMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ExtractionRecordUpdateOne) SetUpdateTime(v time.Time) *ExtractionRecordUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetValues sets the "values" field.
func (_u *ExtractionRecordUpdateOne) SetValues(v map[string]*structpb.Value) *ExtractionRecordUpdateOne {
	_u.mutation.SetValues(v)
	return _u
}

// SetCaptures sets the "captures" field.
func (_u *ExtractionRecordUpdateOne) SetCaptures(v map[string]*browserv1beta.ElementCapture) *ExtractionRecordUpdateOne {
	_u.mutation.SetCaptures(v)
	return _u
}

// SetSchemaID sets the "schema_id" field.
func (_u *ExtractionRecordUpdateOne) SetSchemaID(v uuid.UUID) *ExtractionRecordUpdateOne {
	_u.mutation.SetSchemaID(v)
	return _u
}

// SetNillableSchemaID sets the "schema_id" field if the given value is not nil.
func (_u *ExtractionRecordUpdateOne) SetNillableSchemaID(v *uuid.UUID) *ExtractionRecordUpdateOne {
	if v != nil {
		_u.SetSchemaID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *ExtractionRecordUpdateOne) SetTaskID(v uuid.UUID) *ExtractionRecordUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *ExtractionRecordUpdateOne) SetNillableTaskID(v *uuid.UUID) *ExtractionRecordUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetExtensionID sets the "extension_id" field.
func (_u *ExtractionRecordUpdateOne) SetExtensionID(v string) *ExtractionRecordUpdateOne {
	_u.mutation.SetExtensionID(v)
	return _u
}

// SetNillableExtensionID sets the "extension_id" field if the given value is not nil.
func (_u *ExtractionRecordUpdateOne) SetNillableExtensionID(v *string) *ExtractionRecordUpdateOne {
	if v != nil {
		_u.SetExtensionID(*v)
	}
	return _u
}

// SetSchema sets the "schema" edge to the ExtractionSchema entity.
func (_u *ExtractionRecordUpdateOne) SetSchema(v *ExtractionSchema) *ExtractionRecordUpdateOne {
	return _u.SetSchemaID(v.ID)
}

// Mutation returns the ExtractionRecordMutation object of the builder.
func (_u *ExtractionRecordUpdateOne) Mutation() *ExtractionRecordMutation {
	return _u.mutation
}

// ClearSchema clears the "schema" edge to the ExtractionSchema entity.
func (_u *ExtractionRecordUpdateOne) ClearSchema() *ExtractionRecordUpdateOne {
	_u.mutation.ClearSchema()
	return _u
}

// Where appends a list predicates to the ExtractionRecordUpdate builder.
func (_u *ExtractionRecordUpdateOne) Where(ps ...predicate.ExtractionRecord) *ExtractionRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExtractionRecordUpdateOne) Select(field string, fields ...string) *ExtractionRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExtractionRecord entity.
func (_u *ExtractionRecordUpdateOne) Save(ctx context.Context) (*ExtractionRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExtractionRecordUpdateOne) SaveX(ctx context.Context) *ExtractionRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExtractionRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExtractionRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExtractionRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := extractionrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExtractionRecordUpdateOne) check() error {
	if _u.mutation.SchemaCleared() && len(_u.mutation.SchemaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExtractionRecord.schema"`)
	}
	return nil
}

func (_u *ExtractionRecordUpdateOne) sqlSave(ctx context.Context) (_node *ExtractionRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(extractionrecord.Table, extractionrecord.Columns, sqlgraph.NewFieldSpec(extractionrecord.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExtractionRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, extractionrecord.FieldID)
		for _, f := range fields {
			if !extractionrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != extractionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RowidCleared() {
		_spec.ClearField(extractionrecord.FieldRowid, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(extractionrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Values(); ok {
		vv, err := extractionrecord.ValueScanner.Values.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(extractionrecord.FieldValues, field.TypeBytes, vv)
	}
	if value, ok := _u.mutation.Captures(); ok {
		vv, err := extractionrecord.ValueScanner.Captures.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(extractionrecord.FieldCaptures, field.TypeBytes, vv)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(extractionrecord.FieldTaskID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExtensionID(); ok {
		_spec.SetField(extractionrecord.FieldExtensionID, field.TypeString, value)
	}
	if _u.mutation.SchemaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extractionrecord.SchemaTable,
			Columns: []string{extractionrecord.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchemaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extractionrecord.SchemaTable,
			Columns: []string{extractionrecord.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ExtractionRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{extractionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
