// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionrecord"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// ExtractionRecordQuery is the builder for querying ExtractionRecord entities.
type ExtractionRecordQuery struct {
	config
	ctx        *QueryContext
	order      []extractionrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.ExtractionRecord
	withSchema *ExtractionSchemaQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExtractionRecordQuery builder.
func (_q *ExtractionRecordQuery) Where(ps ...predicate.ExtractionRecord) *ExtractionRecordQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ExtractionRecordQuery) Limit(limit int) *ExtractionRecordQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ExtractionRecordQuery) Offset(offset int) *ExtractionRecordQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ExtractionRecordQuery) Unique(unique bool) *ExtractionRecordQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ExtractionRecordQuery) Order(o ...extractionrecord.OrderOption) *ExtractionRecordQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySchema chains the current query on the "schema" edge.
func (_q *ExtractionRecordQuery) QuerySchema() *ExtractionSchemaQuery {
	query := (&ExtractionSchemaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(extractionrecord.Table, extractionrecord.FieldID, selector),
			sqlgraph.To(extractionschema.Table, extractionschema.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, extractionrecord.SchemaTable, extractionrecord.SchemaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ExtractionRecord entity from the query.
// Returns a *NotFoundError when no ExtractionRecord was found.
func (_q *ExtractionRecordQuery) First(ctx context.Context) (*ExtractionRecord, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{extractionrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ExtractionRecordQuery) FirstX(ctx context.Context) *ExtractionRecord {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExtractionRecord ID from the query.
// Returns a *NotFoundError when no ExtractionRecord ID was found.
func (_q *ExtractionRecordQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{extractionrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ExtractionRecordQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExtractionRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExtractionRecord entity is found.
// Returns a *NotFoundError when no ExtractionRecord entities are found.
func (_q *ExtractionRecordQuery) Only(ctx context.Context) (*ExtractionRecord, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{extractionrecord.Label}
	default:
		return nil, &NotSingularError{extractionrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ExtractionRecordQuery) OnlyX(ctx context.Context) *ExtractionRecord {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExtractionRecord ID in the query.
// Returns a *NotSingularError when more than one ExtractionRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ExtractionRecordQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{extractionrecord.Label}
	default:
		err = &NotSingularError{extractionrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ExtractionRecordQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExtractionRecords.
func (_q *ExtractionRecordQuery) All(ctx context.Context) ([]*ExtractionRecord, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExtractionRecord, *ExtractionRecordQuery]()
	return withInterceptors[[]*ExtractionRecord](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ExtractionRecordQuery) AllX(ctx context.Context) []*ExtractionRecord {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExtractionRecord IDs.
func (_q *ExtractionRecordQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(extractionrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ExtractionRecordQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ExtractionRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ExtractionRecordQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ExtractionRecordQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ExtractionRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ExtractionRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExtractionRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ExtractionRecordQuery) Clone() *ExtractionRecordQuery {
	if _q == nil {
		return nil
	}
	return &ExtractionRecordQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]extractionrecord.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ExtractionRecord{}, _q.predicates...),
		withSchema: _q.withSchema.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSchema tells the query-builder to eager-load the nodes that are connected to
// the "schema" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExtractionRecordQuery) WithSchema(opts ...func(*ExtractionSchemaQuery)) *ExtractionRecordQuery {
	query := (&ExtractionSchemaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSchema = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Rowid int64 `json:"rowid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExtractionRecord.Query().
//		GroupBy(extractionrecord.FieldRowid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ExtractionRecordQuery) GroupBy(field string, fields ...string) *ExtractionRecordGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExtractionRecordGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = extractionrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Rowid int64 `json:"rowid,omitempty"`
//	}
//
//	client.ExtractionRecord.Query().
//		Select(extractionrecord.FieldRowid).
//		Scan(ctx, &v)
func (_q *ExtractionRecordQuery) Select(fields ...string) *ExtractionRecordSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ExtractionRecordSelect{ExtractionRecordQuery: _q}
	sbuild.label = extractionrecord.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExtractionRecordSelect configured with the given aggregations.
func (_q *ExtractionRecordQuery) Aggregate(fns ...AggregateFunc) *ExtractionRecordSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ExtractionRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !extractionrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ExtractionRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExtractionRecord, error) {
	var (
		nodes       = []*ExtractionRecord{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSchema != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExtractionRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExtractionRecord{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSchema; query != nil {
		if err := _q.loadSchema(ctx, query, nodes, nil,
			func(n *ExtractionRecord, e *ExtractionSchema) { n.Edges.Schema = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ExtractionRecordQuery) loadSchema(ctx context.Context, query *ExtractionSchemaQuery, nodes []*ExtractionRecord, init func(*ExtractionRecord), assign func(*ExtractionRecord, *ExtractionSchema)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ExtractionRecord)
	for i := range nodes {
		fk := nodes[i].SchemaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(extractionschema.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "schema_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ExtractionRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ExtractionRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(extractionrecord.Table, extractionrecord.Columns, sqlgraph.NewFieldSpec(extractionrecord.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, extractionrecord.FieldID)
		for i := range fields {
			if fields[i] != extractionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSchema != nil {
			_spec.Node.AddColumnOnce(extractionrecord.FieldSchemaID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ExtractionRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(extractionrecord.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = extractionrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ExtractionRecordQuery) ForUpdate(opts ...sql.LockOption) *ExtractionRecordQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ExtractionRecordQuery) ForShare(opts ...sql.LockOption) *ExtractionRecordQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ExtractionRecordGroupBy is the group-by builder for ExtractionRecord entities.
type ExtractionRecordGroupBy struct {
	selector
	build *ExtractionRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ExtractionRecordGroupBy) Aggregate(fns ...AggregateFunc) *ExtractionRecordGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ExtractionRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExtractionRecordQuery, *ExtractionRecordGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ExtractionRecordGroupBy) sqlScan(ctx context.Context, root *ExtractionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExtractionRecordSelect is the builder for selecting fields of ExtractionRecord entities.
type ExtractionRecordSelect struct {
	*ExtractionRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ExtractionRecordSelect) Aggregate(fns ...AggregateFunc) *ExtractionRecordSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ExtractionRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExtractionRecordQuery, *ExtractionRecordSelect](ctx, _s.ExtractionRecordQuery, _s, _s.inters, v)
}

func (_s *ExtractionRecordSelect) sqlScan(ctx context.Context, root *ExtractionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
