// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionrecord"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/task"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/schema"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/structpb"

	"entgo.io/ent/schema/field"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	extractionrecordMixin := schema.ExtractionRecord{}.Mixin()
	extractionrecordMixinFields0 := extractionrecordMixin[0].Fields()
	_ = extractionrecordMixinFields0
	extractionrecordMixinFields1 := extractionrecordMixin[1].Fields()
	_ = extractionrecordMixinFields1
	extractionrecordFields := schema.ExtractionRecord{}.Fields()
	_ = extractionrecordFields
	// extractionrecordDescCreateTime is the schema descriptor for create_time field.
	extractionrecordDescCreateTime := extractionrecordMixinFields1[0].Descriptor()
	// extractionrecord.DefaultCreateTime holds the default value on creation for the create_time field.
	extractionrecord.DefaultCreateTime = extractionrecordDescCreateTime.Default.(func() time.Time)
	// extractionrecordDescUpdateTime is the schema descriptor for update_time field.
	extractionrecordDescUpdateTime := extractionrecordMixinFields1[1].Descriptor()
	// extractionrecord.DefaultUpdateTime holds the default value on creation for the update_time field.
	extractionrecord.DefaultUpdateTime = extractionrecordDescUpdateTime.Default.(func() time.Time)
	// extractionrecord.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	extractionrecord.UpdateDefaultUpdateTime = extractionrecordDescUpdateTime.UpdateDefault.(func() time.Time)
	// extractionrecordDescValues is the schema descriptor for values field.
	extractionrecordDescValues := extractionrecordFields[0].Descriptor()
	extractionrecord.ValueScanner.Values = extractionrecordDescValues.ValueScanner.(field.TypeValueScanner[map[string]*structpb.Value])
	// extractionrecordDescCaptures is the schema descriptor for captures field.
	extractionrecordDescCaptures := extractionrecordFields[1].Descriptor()
	extractionrecord.ValueScanner.Captures = extractionrecordDescCaptures.ValueScanner.(field.TypeValueScanner[map[string]*browserv1beta.ElementCapture])
	// extractionrecordDescID is the schema descriptor for id field.
	extractionrecordDescID := extractionrecordMixinFields0[0].Descriptor()
	// extractionrecord.DefaultID holds the default value on creation for the id field.
	extractionrecord.DefaultID = extractionrecordDescID.Default.(func() uuid.UUID)
	extractionschemaMixin := schema.ExtractionSchema{}.Mixin()
	extractionschemaMixinFields0 := extractionschemaMixin[0].Fields()
	_ = extractionschemaMixinFields0
	extractionschemaMixinFields1 := extractionschemaMixin[1].Fields()
	_ = extractionschemaMixinFields1
	extractionschemaFields := schema.ExtractionSchema{}.Fields()
	_ = extractionschemaFields
	// extractionschemaDescCreateTime is the schema descriptor for create_time field.
	extractionschemaDescCreateTime := extractionschemaMixinFields1[0].Descriptor()
	// extractionschema.DefaultCreateTime holds the default value on creation for the create_time field.
	extractionschema.DefaultCreateTime = extractionschemaDescCreateTime.Default.(func() time.Time)
	// extractionschemaDescUpdateTime is the schema descriptor for update_time field.
	extractionschemaDescUpdateTime := extractionschemaMixinFields1[1].Descriptor()
	// extractionschema.DefaultUpdateTime holds the default value on creation for the update_time field.
	extractionschema.DefaultUpdateTime = extractionschemaDescUpdateTime.Default.(func() time.Time)
	// extractionschema.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	extractionschema.UpdateDefaultUpdateTime = extractionschemaDescUpdateTime.UpdateDefault.(func() time.Time)
	// extractionschemaDescFields is the schema descriptor for fields field.
	extractionschemaDescFields := extractionschemaFields[2].Descriptor()
	extractionschema.ValueScanner.Fields = extractionschemaDescFields.ValueScanner.(field.TypeValueScanner[[]*browserv1beta.FieldDef])
	// extractionschemaDescID is the schema descriptor for id field.
	extractionschemaDescID := extractionschemaMixinFields0[0].Descriptor()
	// extractionschema.DefaultID holds the default value on creation for the id field.
	extractionschema.DefaultID = extractionschemaDescID.Default.(func() uuid.UUID)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskMixinFields1 := taskMixin[1].Fields()
	_ = taskMixinFields1
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreateTime is the schema descriptor for create_time field.
	taskDescCreateTime := taskMixinFields1[0].Descriptor()
	// task.DefaultCreateTime holds the default value on creation for the create_time field.
	task.DefaultCreateTime = taskDescCreateTime.Default.(func() time.Time)
	// taskDescUpdateTime is the schema descriptor for update_time field.
	taskDescUpdateTime := taskMixinFields1[1].Descriptor()
	// task.DefaultUpdateTime holds the default value on creation for the update_time field.
	task.DefaultUpdateTime = taskDescUpdateTime.Default.(func() time.Time)
	// task.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	task.UpdateDefaultUpdateTime = taskDescUpdateTime.UpdateDefault.(func() time.Time)
	// taskDescState is the schema descriptor for state field.
	taskDescState := taskFields[2].Descriptor()
	task.ValueScanner.State = taskDescState.ValueScanner.(field.TypeValueScanner[browserv1beta.TaskState])
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskMixinFields0[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
}
