// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/task"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRowid sets the "rowid" field.
func (_c *TaskCreate) SetRowid(v int64) *TaskCreate {
	_c.mutation.SetRowid(v)
	return _c
}

// SetNillableRowid sets the "rowid" field if the given value is not nil.
func (_c *TaskCreate) SetNillableRowid(v *int64) *TaskCreate {
	if v != nil {
		_c.SetRowid(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *TaskCreate) SetCreateTime(v time.Time) *TaskCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCreateTime(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TaskCreate) SetUpdateTime(v time.Time) *TaskCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TaskCreate) SetNillableUpdateTime(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *TaskCreate) SetTitle(v string) *TaskCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *TaskCreate) SetURL(v string) *TaskCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetState sets the "state" field.
func (_c *TaskCreate) SetState(v browserv1beta.TaskState) *TaskCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetSchemaID sets the "schema_id" field.
func (_c *TaskCreate) SetSchemaID(v uuid.UUID) *TaskCreate {
	_c.mutation.SetSchemaID(v)
	return _c
}

// SetNillableSchemaID sets the "schema_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableSchemaID(v *uuid.UUID) *TaskCreate {
	if v != nil {
		_c.SetSchemaID(*v)
	}
	return _c
}

// SetRecordID sets the "record_id" field.
func (_c *TaskCreate) SetRecordID(v uuid.UUID) *TaskCreate {
	_c.mutation.SetRecordID(v)
	return _c
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableRecordID(v *uuid.UUID) *TaskCreate {
	if v != nil {
		_c.SetRecordID(*v)
	}
	return _c
}

// SetCompleteTime sets the "complete_time" field.
func (_c *TaskCreate) SetCompleteTime(v time.Time) *TaskCreate {
	_c.mutation.SetCompleteTime(v)
	return _c
}

// SetNillableCompleteTime sets the "complete_time" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCompleteTime(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetCompleteTime(*v)
	}
	return _c
}

// SetExtensionID sets the "extension_id" field.
func (_c *TaskCreate) SetExtensionID(v string) *TaskCreate {
	_c.mutation.SetExtensionID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TaskCreate) SetID(v uuid.UUID) *TaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableID(v *uuid.UUID) *TaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSchema sets the "schema" edge to the ExtractionSchema entity.
func (_c *TaskCreate) SetSchema(v *ExtractionSchema) *TaskCreate {
	return _c.SetSchemaID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := task.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := task.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := task.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Task.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Task.update_time"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Task.title"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Task.url"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Task.state"`)}
	}
	if _, ok := _c.mutation.ExtensionID(); !ok {
		return &ValidationError{Name: "extension_id", err: errors.New(`ent: missing required field "Task.extension_id"`)}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec, error) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Rowid(); ok {
		_spec.SetField(task.FieldRowid, field.TypeInt64, value)
		_node.Rowid = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(task.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(task.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(task.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.State(); ok {
		vv, err := task.ValueScanner.State.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(task.FieldState, field.TypeString, vv)
		_node.State = value
	}
	if value, ok := _c.mutation.RecordID(); ok {
		_spec.SetField(task.FieldRecordID, field.TypeUUID, value)
		_node.RecordID = &value
	}
	if value, ok := _c.mutation.CompleteTime(); ok {
		_spec.SetField(task.FieldCompleteTime, field.TypeTime, value)
		_node.CompleteTime = &value
	}
	if value, ok := _c.mutation.ExtensionID(); ok {
		_spec.SetField(task.FieldExtensionID, field.TypeString, value)
		_node.ExtensionID = value
	}
	if nodes := _c.mutation.SchemaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SchemaTable,
			Columns: []string{task.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SchemaID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Task.Create().
//		SetRowid(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskUpsert) {
//			SetRowid(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskCreate) OnConflict(opts ...sql.ConflictOption) *TaskUpsertOne {
	_c.conflict = opts
	return &TaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskCreate) OnConflictColumns(columns ...string) *TaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskUpsertOne{
		create: _c,
	}
}

type (
	// TaskUpsertOne is the builder for "upsert"-ing
	//  one Task node.
	TaskUpsertOne struct {
		create *TaskCreate
	}

	// TaskUpsert is the "OnConflict" setter.
	TaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *TaskUpsert) SetUpdateTime(v time.Time) *TaskUpsert {
	u.Set(task.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TaskUpsert) UpdateUpdateTime() *TaskUpsert {
	u.SetExcluded(task.FieldUpdateTime)
	return u
}

// SetTitle sets the "title" field.
func (u *TaskUpsert) SetTitle(v string) *TaskUpsert {
	u.Set(task.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TaskUpsert) UpdateTitle() *TaskUpsert {
	u.SetExcluded(task.FieldTitle)
	return u
}

// SetURL sets the "url" field.
func (u *TaskUpsert) SetURL(v string) *TaskUpsert {
	u.Set(task.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TaskUpsert) UpdateURL() *TaskUpsert {
	u.SetExcluded(task.FieldURL)
	return u
}

// SetState sets the "state" field.
func (u *TaskUpsert) SetState(v browserv1beta.TaskState) *TaskUpsert {
	u.Set(task.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TaskUpsert) UpdateState() *TaskUpsert {
	u.SetExcluded(task.FieldState)
	return u
}

// SetSchemaID sets the "schema_id" field.
func (u *TaskUpsert) SetSchemaID(v uuid.UUID) *TaskUpsert {
	u.Set(task.FieldSchemaID, v)
	return u
}

// UpdateSchemaID sets the "schema_id" field to the value that was provided on create.
func (u *TaskUpsert) UpdateSchemaID() *TaskUpsert {
	u.SetExcluded(task.FieldSchemaID)
	return u
}

// ClearSchemaID clears the value of the "schema_id" field.
func (u *TaskUpsert) ClearSchemaID() *TaskUpsert {
	u.SetNull(task.FieldSchemaID)
	return u
}

// SetRecordID sets the "record_id" field.
func (u *TaskUpsert) SetRecordID(v uuid.UUID) *TaskUpsert {
	u.Set(task.FieldRecordID, v)
	return u
}

// UpdateRecordID sets the "record_id" field to the value that was provided on create.
func (u *TaskUpsert) UpdateRecordID() *TaskUpsert {
	u.SetExcluded(task.FieldRecordID)
	return u
}

// ClearRecordID clears the value of the "record_id" field.
func (u *TaskUpsert) ClearRecordID() *TaskUpsert {
	u.SetNull(task.FieldRecordID)
	return u
}

// SetCompleteTime sets the "complete_time" field.
func (u *TaskUpsert) SetCompleteTime(v time.Time) *TaskUpsert {
	u.Set(task.FieldCompleteTime, v)
	return u
}

// UpdateCompleteTime sets the "complete_time" field to the value that was provided on create.
func (u *TaskUpsert) UpdateCompleteTime() *TaskUpsert {
	u.SetExcluded(task.FieldCompleteTime)
	return u
}

// ClearCompleteTime clears the value of the "complete_time" field.
func (u *TaskUpsert) ClearCompleteTime() *TaskUpsert {
	u.SetNull(task.FieldCompleteTime)
	return u
}

// SetExtensionID sets the "extension_id" field.
func (u *TaskUpsert) SetExtensionID(v string) *TaskUpsert {
	u.Set(task.FieldExtensionID, v)
	return u
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *TaskUpsert) UpdateExtensionID() *TaskUpsert {
	u.SetExcluded(task.FieldExtensionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(task.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskUpsertOne) UpdateNewValues() *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(task.FieldID)
		}
		if _, exists := u.create.mutation.Rowid(); exists {
			s.SetIgnore(task.FieldRowid)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(task.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Task.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskUpsertOne) Ignore() *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskUpsertOne) DoNothing() *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskCreate.OnConflict
// documentation for more info.
func (u *TaskUpsertOne) Update(set func(*TaskUpsert)) *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TaskUpsertOne) SetUpdateTime(v time.Time) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateUpdateTime() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetTitle sets the "title" field.
func (u *TaskUpsertOne) SetTitle(v string) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateTitle() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateTitle()
	})
}

// SetURL sets the "url" field.
func (u *TaskUpsertOne) SetURL(v string) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateURL() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateURL()
	})
}

// SetState sets the "state" field.
func (u *TaskUpsertOne) SetState(v browserv1beta.TaskState) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateState() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateState()
	})
}

// SetSchemaID sets the "schema_id" field.
func (u *TaskUpsertOne) SetSchemaID(v uuid.UUID) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetSchemaID(v)
	})
}

// UpdateSchemaID sets the "schema_id" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateSchemaID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateSchemaID()
	})
}

// ClearSchemaID clears the value of the "schema_id" field.
func (u *TaskUpsertOne) ClearSchemaID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.ClearSchemaID()
	})
}

// SetRecordID sets the "record_id" field.
func (u *TaskUpsertOne) SetRecordID(v uuid.UUID) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetRecordID(v)
	})
}

// UpdateRecordID sets the "record_id" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateRecordID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateRecordID()
	})
}

// ClearRecordID clears the value of the "record_id" field.
func (u *TaskUpsertOne) ClearRecordID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.ClearRecordID()
	})
}

// SetCompleteTime sets the "complete_time" field.
func (u *TaskUpsertOne) SetCompleteTime(v time.Time) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetCompleteTime(v)
	})
}

// UpdateCompleteTime sets the "complete_time" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateCompleteTime() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateCompleteTime()
	})
}

// ClearCompleteTime clears the value of the "complete_time" field.
func (u *TaskUpsertOne) ClearCompleteTime() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.ClearCompleteTime()
	})
}

// SetExtensionID sets the "extension_id" field.
func (u *TaskUpsertOne) SetExtensionID(v string) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetExtensionID(v)
	})
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateExtensionID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateExtensionID()
	})
}

// Exec executes the query.
func (u *TaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TaskUpsertOne.ID is not supported by MySQL driver. Use TaskUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
	conflict []sql.ConflictOption
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Task.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskUpsert) {
//			SetRowid(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskUpsertBulk {
	_c.conflict = opts
	return &TaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskCreateBulk) OnConflictColumns(columns ...string) *TaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskUpsertBulk{
		create: _c,
	}
}

// TaskUpsertBulk is the builder for "upsert"-ing
// a bulk of Task nodes.
type TaskUpsertBulk struct {
	create *TaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(task.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskUpsertBulk) UpdateNewValues() *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(task.FieldID)
			}
			if _, exists := b.mutation.Rowid(); exists {
				s.SetIgnore(task.FieldRowid)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(task.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskUpsertBulk) Ignore() *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskUpsertBulk) DoNothing() *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskCreateBulk.OnConflict
// documentation for more info.
func (u *TaskUpsertBulk) Update(set func(*TaskUpsert)) *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TaskUpsertBulk) SetUpdateTime(v time.Time) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateUpdateTime() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetTitle sets the "title" field.
func (u *TaskUpsertBulk) SetTitle(v string) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateTitle() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateTitle()
	})
}

// SetURL sets the "url" field.
func (u *TaskUpsertBulk) SetURL(v string) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateURL() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateURL()
	})
}

// SetState sets the "state" field.
func (u *TaskUpsertBulk) SetState(v browserv1beta.TaskState) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateState() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateState()
	})
}

// SetSchemaID sets the "schema_id" field.
func (u *TaskUpsertBulk) SetSchemaID(v uuid.UUID) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetSchemaID(v)
	})
}

// UpdateSchemaID sets the "schema_id" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateSchemaID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateSchemaID()
	})
}

// ClearSchemaID clears the value of the "schema_id" field.
func (u *TaskUpsertBulk) ClearSchemaID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.ClearSchemaID()
	})
}

// SetRecordID sets the "record_id" field.
func (u *TaskUpsertBulk) SetRecordID(v uuid.UUID) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetRecordID(v)
	})
}

// UpdateRecordID sets the "record_id" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateRecordID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateRecordID()
	})
}

// ClearRecordID clears the value of the "record_id" field.
func (u *TaskUpsertBulk) ClearRecordID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.ClearRecordID()
	})
}

// SetCompleteTime sets the "complete_time" field.
func (u *TaskUpsertBulk) SetCompleteTime(v time.Time) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetCompleteTime(v)
	})
}

// UpdateCompleteTime sets the "complete_time" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateCompleteTime() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateCompleteTime()
	})
}

// ClearCompleteTime clears the value of the "complete_time" field.
func (u *TaskUpsertBulk) ClearCompleteTime() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.ClearCompleteTime()
	})
}

// SetExtensionID sets the "extension_id" field.
func (u *TaskUpsertBulk) SetExtensionID(v string) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetExtensionID(v)
	})
}

// UpdateExtensionID sets the "extension_id" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateExtensionID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateExtensionID()
	})
}

// Exec executes the query.
func (u *TaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
