// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/extractionschema"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/predicate"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/task"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TaskUpdate) SetUpdateTime(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTitle(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TaskUpdate) SetURL(v string) *TaskUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableURL(v *string) *TaskUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *TaskUpdate) SetState(v browserv1beta.TaskState) *TaskUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableState(v *browserv1beta.TaskState) *TaskUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetSchemaID sets the "schema_id" field.
func (_u *TaskUpdate) SetSchemaID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetSchemaID(v)
	return _u
}

// SetNillableSchemaID sets the "schema_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSchemaID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetSchemaID(*v)
	}
	return _u
}

// ClearSchemaID clears the value of the "schema_id" field.
func (_u *TaskUpdate) ClearSchemaID() *TaskUpdate {
	_u.mutation.ClearSchemaID()
	return _u
}

// SetRecordID sets the "record_id" field.
func (_u *TaskUpdate) SetRecordID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetRecordID(v)
	return _u
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableRecordID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetRecordID(*v)
	}
	return _u
}

// ClearRecordID clears the value of the "record_id" field.
func (_u *TaskUpdate) ClearRecordID() *TaskUpdate {
	_u.mutation.ClearRecordID()
	return _u
}

// SetCompleteTime sets the "complete_time" field.
func (_u *TaskUpdate) SetCompleteTime(v time.Time) *TaskUpdate {
	_u.mutation.SetCompleteTime(v)
	return _u
}

// SetNillableCompleteTime sets the "complete_time" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCompleteTime(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetCompleteTime(*v)
	}
	return _u
}

// ClearCompleteTime clears the value of the "complete_time" field.
func (_u *TaskUpdate) ClearCompleteTime() *TaskUpdate {
	_u.mutation.ClearCompleteTime()
	return _u
}

// SetExtensionID sets the "extension_id" field.
func (_u *TaskUpdate) SetExtensionID(v string) *TaskUpdate {
	_u.mutation.SetExtensionID(v)
	return _u
}

// SetNillableExtensionID sets the "extension_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableExtensionID(v *string) *TaskUpdate {
	if v != nil {
		_u.SetExtensionID(*v)
	}
	return _u
}

// SetSchema sets the "schema" edge to the ExtractionSchema entity.
func (_u *TaskUpdate) SetSchema(v *ExtractionSchema) *TaskUpdate {
	return _u.SetSchemaID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSchema clears the "schema" edge to the ExtractionSchema entity.
func (_u *TaskUpdate) ClearSchema() *TaskUpdate {
	_u.mutation.ClearSchema()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := task.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RowidCleared() {
		_spec.ClearField(task.FieldRowid, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(task.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(task.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		vv, err := task.ValueScanner.State.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(task.FieldState, field.TypeString, vv)
	}
	if value, ok := _u.mutation.RecordID(); ok {
		_spec.SetField(task.FieldRecordID, field.TypeUUID, value)
	}
	if _u.mutation.RecordIDCleared() {
		_spec.ClearField(task.FieldRecordID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CompleteTime(); ok {
		_spec.SetField(task.FieldCompleteTime, field.TypeTime, value)
	}
	if _u.mutation.CompleteTimeCleared() {
		_spec.ClearField(task.FieldCompleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ExtensionID(); ok {
		_spec.SetField(task.FieldExtensionID, field.TypeString, value)
	}
	if _u.mutation.SchemaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SchemaTable,
			Columns: []string{task.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchemaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SchemaTable,
			Columns: []string{task.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *TaskUpdateOne) SetUpdateTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdateOne) SetTitle(v string) *TaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTitle(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TaskUpdateOne) SetURL(v string) *TaskUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableURL(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *TaskUpdateOne) SetState(v browserv1beta.TaskState) *TaskUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableState(v *browserv1beta.TaskState) *TaskUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetSchemaID sets the "schema_id" field.
func (_u *TaskUpdateOne) SetSchemaID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetSchemaID(v)
	return _u
}

// SetNillableSchemaID sets the "schema_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSchemaID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetSchemaID(*v)
	}
	return _u
}

// ClearSchemaID clears the value of the "schema_id" field.
func (_u *TaskUpdateOne) ClearSchemaID() *TaskUpdateOne {
	_u.mutation.ClearSchemaID()
	return _u
}

// SetRecordID sets the "record_id" field.
func (_u *TaskUpdateOne) SetRecordID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetRecordID(v)
	return _u
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableRecordID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetRecordID(*v)
	}
	return _u
}

// ClearRecordID clears the value of the "record_id" field.
func (_u *TaskUpdateOne) ClearRecordID() *TaskUpdateOne {
	_u.mutation.ClearRecordID()
	return _u
}

// SetCompleteTime sets the "complete_time" field.
func (_u *TaskUpdateOne) SetCompleteTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetCompleteTime(v)
	return _u
}

// SetNillableCompleteTime sets the "complete_time" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCompleteTime(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetCompleteTime(*v)
	}
	return _u
}

// ClearCompleteTime clears the value of the "complete_time" field.
func (_u *TaskUpdateOne) ClearCompleteTime() *TaskUpdateOne {
	_u.mutation.ClearCompleteTime()
	return _u
}

// SetExtensionID sets the "extension_id" field.
func (_u *TaskUpdateOne) SetExtensionID(v string) *TaskUpdateOne {
	_u.mutation.SetExtensionID(v)
	return _u
}

// SetNillableExtensionID sets the "extension_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableExtensionID(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetExtensionID(*v)
	}
	return _u
}

// SetSchema sets the "schema" edge to the ExtractionSchema entity.
func (_u *TaskUpdateOne) SetSchema(v *ExtractionSchema) *TaskUpdateOne {
	return _u.SetSchemaID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSchema clears the "schema" edge to the ExtractionSchema entity.
func (_u *TaskUpdateOne) ClearSchema() *TaskUpdateOne {
	_u.mutation.ClearSchema()
	return _u
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := task.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RowidCleared() {
		_spec.ClearField(task.FieldRowid, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(task.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(task.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		vv, err := task.ValueScanner.State.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(task.FieldState, field.TypeString, vv)
	}
	if value, ok := _u.mutation.RecordID(); ok {
		_spec.SetField(task.FieldRecordID, field.TypeUUID, value)
	}
	if _u.mutation.RecordIDCleared() {
		_spec.ClearField(task.FieldRecordID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CompleteTime(); ok {
		_spec.SetField(task.FieldCompleteTime, field.TypeTime, value)
	}
	if _u.mutation.CompleteTimeCleared() {
		_spec.ClearField(task.FieldCompleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ExtensionID(); ok {
		_spec.SetField(task.FieldExtensionID, field.TypeString, value)
	}
	if _u.mutation.SchemaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SchemaTable,
			Columns: []string{task.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchemaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SchemaTable,
			Columns: []string{task.SchemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(extractionschema.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
