// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file integration/browser/v1beta/config.proto (package integration.browser.v1beta, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ChromeConfig, ChromeConfigValid } from "./chrome_pb";
import { file_integration_browser_v1beta_chrome } from "./chrome_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file integration/browser/v1beta/config.proto.
 */
export const file_integration_browser_v1beta_config: GenFile = /*@__PURE__*/
  fileDesc("CidpbnRlZ3JhdGlvbi9icm93c2VyL3YxYmV0YS9jb25maWcucHJvdG8SGmludGVncmF0aW9uLmJyb3dzZXIudjFiZXRhIlYKBkNvbmZpZxI6CgZjaHJvbWUYASABKAsyKC5pbnRlZ3JhdGlvbi5icm93c2VyLnYxYmV0YS5DaHJvbWVDb25maWdIAEIQCgdicm93c2VyEgW6SAIIAUKcAgoeY29tLmludGVncmF0aW9uLmJyb3dzZXIudjFiZXRhQgtDb25maWdQcm90b1ABWmNnaXRodWIuY29tL2RhdGFraXQtZGV2L2R0a3QtaW50ZWdyYXRpb25zL2Jyb3dzZXIvcGtnL3Byb3RvL2ludGVncmF0aW9uL2Jyb3dzZXIvdjFiZXRhO2Jyb3dzZXJ2MWJldGGiAgNJQliqAhpJbnRlZ3JhdGlvbi5Ccm93c2VyLlYxYmV0YcoCGkludGVncmF0aW9uXEJyb3dzZXJcVjFiZXRh4gImSW50ZWdyYXRpb25cQnJvd3NlclxWMWJldGFcR1BCTWV0YWRhdGHqAhxJbnRlZ3JhdGlvbjo6QnJvd3Nlcjo6VjFiZXRhYgZwcm90bzM", [file_buf_validate_validate, file_integration_browser_v1beta_chrome]);

/**
 * @generated from message integration.browser.v1beta.Config
 */
export type Config = Message<"integration.browser.v1beta.Config"> & {
  /**
   * @generated from oneof integration.browser.v1beta.Config.browser
   */
  browser: {
    /**
     * @generated from field: integration.browser.v1beta.ChromeConfig chrome = 1;
     */
    value: ChromeConfig;
    case: "chrome";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message integration.browser.v1beta.Config
 */
export type ConfigValid = Message<"integration.browser.v1beta.Config"> & {
  /**
   * @generated from oneof integration.browser.v1beta.Config.browser
   */
  browser: {
    /**
     * @generated from field: integration.browser.v1beta.ChromeConfig chrome = 1;
     */
    value: ChromeConfigValid;
    case: "chrome";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message integration.browser.v1beta.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export const ConfigSchema: GenMessage<Config, {validType: ConfigValid}> = /*@__PURE__*/
  messageDesc(file_integration_browser_v1beta_config, 0);

