// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: integration/testbin/v1beta/inspect_service.proto

package v1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnythingRequest -- input to Anything.
type AnythingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Free-form payload echoed back unchanged in AnythingResponse.payload.
	Payload       *structpb.Value `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnythingRequest) Reset() {
	*x = AnythingRequest{}
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnythingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnythingRequest) ProtoMessage() {}

func (x *AnythingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnythingRequest.ProtoReflect.Descriptor instead.
func (*AnythingRequest) Descriptor() ([]byte, []int) {
	return file_integration_testbin_v1beta_inspect_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnythingRequest) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

// AnythingResponse describes the incoming RPC from the server's
// perspective.
type AnythingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully-qualified gRPC method, e.g.
	// "/integration.testbin.v1beta.InspectService/Anything".
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Incoming request metadata as received. gRPC normalizes keys to
	// lowercase. Values for binary metadata (keys ending in `-bin`)
	// are base64-encoded so they fit in a string field.
	Metadata map[string]*StringValues `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Wall-clock deadline derived from the incoming context. Unset if
	// the caller did not propagate one.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Network peer's address as reported by gRPC.
	Peer string `protobuf:"bytes,4,opt,name=peer,proto3" json:"peer,omitempty"`
	// Verbatim copy of the request payload.
	Payload       *structpb.Value `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnythingResponse) Reset() {
	*x = AnythingResponse{}
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnythingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnythingResponse) ProtoMessage() {}

func (x *AnythingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnythingResponse.ProtoReflect.Descriptor instead.
func (*AnythingResponse) Descriptor() ([]byte, []int) {
	return file_integration_testbin_v1beta_inspect_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnythingResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AnythingResponse) GetMetadata() map[string]*StringValues {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnythingResponse) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *AnythingResponse) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *AnythingResponse) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

// StringValues holds an ordered list of values for a single
// metadata key. Wrapper exists because proto3 forbids
// `map<K, repeated V>` directly.
type StringValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Values for the key, in receipt order. Multi-valued metadata is
	// preserved; binary (`-bin`) values are base64-encoded.
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValues) Reset() {
	*x = StringValues{}
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValues) ProtoMessage() {}

func (x *StringValues) ProtoReflect() protoreflect.Message {
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValues.ProtoReflect.Descriptor instead.
func (*StringValues) Descriptor() ([]byte, []int) {
	return file_integration_testbin_v1beta_inspect_service_proto_rawDescGZIP(), []int{2}
}

func (x *StringValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// GetConfigRequest -- input to GetConfig. Takes no parameters.
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_integration_testbin_v1beta_inspect_service_proto_rawDescGZIP(), []int{3}
}

// GetConfigResponse holds the instance's current Config payload.
type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot of Config.payload at instance construction. testbin
	// does not mutate or interpret this value.
	Payload       *structpb.Value `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_testbin_v1beta_inspect_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_integration_testbin_v1beta_inspect_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigResponse) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_integration_testbin_v1beta_inspect_service_proto protoreflect.FileDescriptor

const file_integration_testbin_v1beta_inspect_service_proto_rawDesc = "" +
	"\n" +
	"0integration/testbin/v1beta/inspect_service.proto\x12\x1aintegration.testbin.v1beta\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x0fAnythingRequest\x120\n" +
	"\apayload\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\apayload\"\xe7\x02\n" +
	"\x10AnythingResponse\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12V\n" +
	"\bmetadata\x18\x02 \x03(\v2:.integration.testbin.v1beta.AnythingResponse.MetadataEntryR\bmetadata\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x12\n" +
	"\x04peer\x18\x04 \x01(\tR\x04peer\x120\n" +
	"\apayload\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\apayload\x1ae\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.integration.testbin.v1beta.StringValuesR\x05value:\x028\x01\"&\n" +
	"\fStringValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x12\n" +
	"\x10GetConfigRequest\"E\n" +
	"\x11GetConfigResponse\x120\n" +
	"\apayload\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\apayload2\xe1\x01\n" +
	"\x0eInspectService\x12e\n" +
	"\bAnything\x12+.integration.testbin.v1beta.AnythingRequest\x1a,.integration.testbin.v1beta.AnythingResponse\x12h\n" +
	"\tGetConfig\x12,.integration.testbin.v1beta.GetConfigRequest\x1a-.integration.testbin.v1beta.GetConfigResponseBQZOgithub.com/datakit-dev/dtkt-integrations/testbin/pkg/integration/testbin/v1betab\x06proto3"

var (
	file_integration_testbin_v1beta_inspect_service_proto_rawDescOnce sync.Once
	file_integration_testbin_v1beta_inspect_service_proto_rawDescData []byte
)

func file_integration_testbin_v1beta_inspect_service_proto_rawDescGZIP() []byte {
	file_integration_testbin_v1beta_inspect_service_proto_rawDescOnce.Do(func() {
		file_integration_testbin_v1beta_inspect_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_testbin_v1beta_inspect_service_proto_rawDesc), len(file_integration_testbin_v1beta_inspect_service_proto_rawDesc)))
	})
	return file_integration_testbin_v1beta_inspect_service_proto_rawDescData
}

var file_integration_testbin_v1beta_inspect_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_integration_testbin_v1beta_inspect_service_proto_goTypes = []any{
	(*AnythingRequest)(nil),       // 0: integration.testbin.v1beta.AnythingRequest
	(*AnythingResponse)(nil),      // 1: integration.testbin.v1beta.AnythingResponse
	(*StringValues)(nil),          // 2: integration.testbin.v1beta.StringValues
	(*GetConfigRequest)(nil),      // 3: integration.testbin.v1beta.GetConfigRequest
	(*GetConfigResponse)(nil),     // 4: integration.testbin.v1beta.GetConfigResponse
	nil,                           // 5: integration.testbin.v1beta.AnythingResponse.MetadataEntry
	(*structpb.Value)(nil),        // 6: google.protobuf.Value
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_integration_testbin_v1beta_inspect_service_proto_depIdxs = []int32{
	6, // 0: integration.testbin.v1beta.AnythingRequest.payload:type_name -> google.protobuf.Value
	5, // 1: integration.testbin.v1beta.AnythingResponse.metadata:type_name -> integration.testbin.v1beta.AnythingResponse.MetadataEntry
	7, // 2: integration.testbin.v1beta.AnythingResponse.deadline:type_name -> google.protobuf.Timestamp
	6, // 3: integration.testbin.v1beta.AnythingResponse.payload:type_name -> google.protobuf.Value
	6, // 4: integration.testbin.v1beta.GetConfigResponse.payload:type_name -> google.protobuf.Value
	2, // 5: integration.testbin.v1beta.AnythingResponse.MetadataEntry.value:type_name -> integration.testbin.v1beta.StringValues
	0, // 6: integration.testbin.v1beta.InspectService.Anything:input_type -> integration.testbin.v1beta.AnythingRequest
	3, // 7: integration.testbin.v1beta.InspectService.GetConfig:input_type -> integration.testbin.v1beta.GetConfigRequest
	1, // 8: integration.testbin.v1beta.InspectService.Anything:output_type -> integration.testbin.v1beta.AnythingResponse
	4, // 9: integration.testbin.v1beta.InspectService.GetConfig:output_type -> integration.testbin.v1beta.GetConfigResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_integration_testbin_v1beta_inspect_service_proto_init() }
func file_integration_testbin_v1beta_inspect_service_proto_init() {
	if File_integration_testbin_v1beta_inspect_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_testbin_v1beta_inspect_service_proto_rawDesc), len(file_integration_testbin_v1beta_inspect_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integration_testbin_v1beta_inspect_service_proto_goTypes,
		DependencyIndexes: file_integration_testbin_v1beta_inspect_service_proto_depIdxs,
		MessageInfos:      file_integration_testbin_v1beta_inspect_service_proto_msgTypes,
	}.Build()
	File_integration_testbin_v1beta_inspect_service_proto = out.File
	file_integration_testbin_v1beta_inspect_service_proto_goTypes = nil
	file_integration_testbin_v1beta_inspect_service_proto_depIdxs = nil
}
