# yaml-language-server: $schema=http://localhost:9900/schemas/dtkt.integrationsdk.v1beta1.Package.jsonschema.json
kind: Package
apiVersion: v1beta1
spec:
  identity:
    name: MetaBusiness
    version: 0.1.0
  description: MetaBusiness description...
  icon: https://address.to/icon.png
  type: PACKAGE_TYPE_GO
  build: {}
