// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: integration/sheets/v1beta/spreadsheet.proto

package v1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpreadsheetService_AppendSpreadsheetValues_FullMethodName = "/integration.sheets.v1beta.SpreadsheetService/AppendSpreadsheetValues"
	SpreadsheetService_GetSpreadsheetValues_FullMethodName    = "/integration.sheets.v1beta.SpreadsheetService/GetSpreadsheetValues"
	SpreadsheetService_ListSpreadsheets_FullMethodName        = "/integration.sheets.v1beta.SpreadsheetService/ListSpreadsheets"
)

// SpreadsheetServiceClient is the client API for SpreadsheetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpreadsheetService provides a gRPC interface for interacting with Google Sheets spreadsheets.
type SpreadsheetServiceClient interface {
	// AppendSpreadsheetValues appends rows of data to a specified range in a spreadsheet.
	AppendSpreadsheetValues(ctx context.Context, in *AppendSpreadsheetValuesRequest, opts ...grpc.CallOption) (*AppendSpreadsheetValuesResponse, error)
	// GetSpreadsheetValues retrieves values from a specified range in a spreadsheet.
	GetSpreadsheetValues(ctx context.Context, in *GetSpreadsheetValuesRequest, opts ...grpc.CallOption) (*GetSpreadsheetValuesResponse, error)
	// ListSpreadsheets returns a list of all accessible spreadsheets.
	ListSpreadsheets(ctx context.Context, in *ListSpreadsheetsRequest, opts ...grpc.CallOption) (*ListSpreadsheetsResponse, error)
}

type spreadsheetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpreadsheetServiceClient(cc grpc.ClientConnInterface) SpreadsheetServiceClient {
	return &spreadsheetServiceClient{cc}
}

func (c *spreadsheetServiceClient) AppendSpreadsheetValues(ctx context.Context, in *AppendSpreadsheetValuesRequest, opts ...grpc.CallOption) (*AppendSpreadsheetValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendSpreadsheetValuesResponse)
	err := c.cc.Invoke(ctx, SpreadsheetService_AppendSpreadsheetValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spreadsheetServiceClient) GetSpreadsheetValues(ctx context.Context, in *GetSpreadsheetValuesRequest, opts ...grpc.CallOption) (*GetSpreadsheetValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpreadsheetValuesResponse)
	err := c.cc.Invoke(ctx, SpreadsheetService_GetSpreadsheetValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spreadsheetServiceClient) ListSpreadsheets(ctx context.Context, in *ListSpreadsheetsRequest, opts ...grpc.CallOption) (*ListSpreadsheetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpreadsheetsResponse)
	err := c.cc.Invoke(ctx, SpreadsheetService_ListSpreadsheets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpreadsheetServiceServer is the server API for SpreadsheetService service.
// All implementations must embed UnimplementedSpreadsheetServiceServer
// for forward compatibility.
//
// SpreadsheetService provides a gRPC interface for interacting with Google Sheets spreadsheets.
type SpreadsheetServiceServer interface {
	// AppendSpreadsheetValues appends rows of data to a specified range in a spreadsheet.
	AppendSpreadsheetValues(context.Context, *AppendSpreadsheetValuesRequest) (*AppendSpreadsheetValuesResponse, error)
	// GetSpreadsheetValues retrieves values from a specified range in a spreadsheet.
	GetSpreadsheetValues(context.Context, *GetSpreadsheetValuesRequest) (*GetSpreadsheetValuesResponse, error)
	// ListSpreadsheets returns a list of all accessible spreadsheets.
	ListSpreadsheets(context.Context, *ListSpreadsheetsRequest) (*ListSpreadsheetsResponse, error)
	mustEmbedUnimplementedSpreadsheetServiceServer()
}

// UnimplementedSpreadsheetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpreadsheetServiceServer struct{}

func (UnimplementedSpreadsheetServiceServer) AppendSpreadsheetValues(context.Context, *AppendSpreadsheetValuesRequest) (*AppendSpreadsheetValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendSpreadsheetValues not implemented")
}
func (UnimplementedSpreadsheetServiceServer) GetSpreadsheetValues(context.Context, *GetSpreadsheetValuesRequest) (*GetSpreadsheetValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpreadsheetValues not implemented")
}
func (UnimplementedSpreadsheetServiceServer) ListSpreadsheets(context.Context, *ListSpreadsheetsRequest) (*ListSpreadsheetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpreadsheets not implemented")
}
func (UnimplementedSpreadsheetServiceServer) mustEmbedUnimplementedSpreadsheetServiceServer() {}
func (UnimplementedSpreadsheetServiceServer) testEmbeddedByValue()                            {}

// UnsafeSpreadsheetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpreadsheetServiceServer will
// result in compilation errors.
type UnsafeSpreadsheetServiceServer interface {
	mustEmbedUnimplementedSpreadsheetServiceServer()
}

func RegisterSpreadsheetServiceServer(s grpc.ServiceRegistrar, srv SpreadsheetServiceServer) {
	// If the following call panics, it indicates UnimplementedSpreadsheetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpreadsheetService_ServiceDesc, srv)
}

func _SpreadsheetService_AppendSpreadsheetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendSpreadsheetValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpreadsheetServiceServer).AppendSpreadsheetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpreadsheetService_AppendSpreadsheetValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpreadsheetServiceServer).AppendSpreadsheetValues(ctx, req.(*AppendSpreadsheetValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpreadsheetService_GetSpreadsheetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpreadsheetValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpreadsheetServiceServer).GetSpreadsheetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpreadsheetService_GetSpreadsheetValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpreadsheetServiceServer).GetSpreadsheetValues(ctx, req.(*GetSpreadsheetValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpreadsheetService_ListSpreadsheets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpreadsheetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpreadsheetServiceServer).ListSpreadsheets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpreadsheetService_ListSpreadsheets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpreadsheetServiceServer).ListSpreadsheets(ctx, req.(*ListSpreadsheetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpreadsheetService_ServiceDesc is the grpc.ServiceDesc for SpreadsheetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpreadsheetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integration.sheets.v1beta.SpreadsheetService",
	HandlerType: (*SpreadsheetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendSpreadsheetValues",
			Handler:    _SpreadsheetService_AppendSpreadsheetValues_Handler,
		},
		{
			MethodName: "GetSpreadsheetValues",
			Handler:    _SpreadsheetService_GetSpreadsheetValues_Handler,
		},
		{
			MethodName: "ListSpreadsheets",
			Handler:    _SpreadsheetService_ListSpreadsheets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integration/sheets/v1beta/spreadsheet.proto",
}
