// Code generated by ent, DO NOT EDIT.

package task

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRowid holds the string denoting the rowid field in the database.
	FieldRowid = "rowid"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldSchemaID holds the string denoting the schema_id field in the database.
	FieldSchemaID = "schema_id"
	// FieldRecordID holds the string denoting the record_id field in the database.
	FieldRecordID = "record_id"
	// FieldCompleteTime holds the string denoting the complete_time field in the database.
	FieldCompleteTime = "complete_time"
	// FieldExtensionID holds the string denoting the extension_id field in the database.
	FieldExtensionID = "extension_id"
	// EdgeSchema holds the string denoting the schema edge name in mutations.
	EdgeSchema = "schema"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// SchemaTable is the table that holds the schema relation/edge.
	SchemaTable = "tasks"
	// SchemaInverseTable is the table name for the ExtractionSchema entity.
	// It exists in this package in order to avoid circular dependency with the "extractionschema" package.
	SchemaInverseTable = "extraction_schemas"
	// SchemaColumn is the table column denoting the schema relation/edge.
	SchemaColumn = "schema_id"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldRowid,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTitle,
	FieldURL,
	FieldState,
	FieldSchemaID,
	FieldRecordID,
	FieldCompleteTime,
	FieldExtensionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
	// ValueScanner of all Task fields.
	ValueScanner struct {
		State field.TypeValueScanner[browserv1beta.TaskState]
	}
)

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRowid orders the results by the rowid field.
func ByRowid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRowid, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// BySchemaID orders the results by the schema_id field.
func BySchemaID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaID, opts...).ToFunc()
}

// ByRecordID orders the results by the record_id field.
func ByRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordID, opts...).ToFunc()
}

// ByCompleteTime orders the results by the complete_time field.
func ByCompleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleteTime, opts...).ToFunc()
}

// ByExtensionID orders the results by the extension_id field.
func ByExtensionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtensionID, opts...).ToFunc()
}

// BySchemaField orders the results by schema field.
func BySchemaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSchemaStep(), sql.OrderByField(field, opts...))
	}
}
func newSchemaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SchemaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SchemaTable, SchemaColumn),
	)
}
