// Code generated by ent, DO NOT EDIT.

package task

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/predicate"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// Rowid applies equality check predicate on the "rowid" field. It's identical to RowidEQ.
func Rowid(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRowid, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdateTime, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldURL, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	return predicate.TaskOrErr(sql.FieldEQ(FieldState, vc), err)
}

// SchemaID applies equality check predicate on the "schema_id" field. It's identical to SchemaIDEQ.
func SchemaID(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldSchemaID, v))
}

// RecordID applies equality check predicate on the "record_id" field. It's identical to RecordIDEQ.
func RecordID(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRecordID, v))
}

// CompleteTime applies equality check predicate on the "complete_time" field. It's identical to CompleteTimeEQ.
func CompleteTime(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCompleteTime, v))
}

// ExtensionID applies equality check predicate on the "extension_id" field. It's identical to ExtensionIDEQ.
func ExtensionID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldExtensionID, v))
}

// RowidEQ applies the EQ predicate on the "rowid" field.
func RowidEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRowid, v))
}

// RowidNEQ applies the NEQ predicate on the "rowid" field.
func RowidNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldRowid, v))
}

// RowidIn applies the In predicate on the "rowid" field.
func RowidIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldRowid, vs...))
}

// RowidNotIn applies the NotIn predicate on the "rowid" field.
func RowidNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldRowid, vs...))
}

// RowidGT applies the GT predicate on the "rowid" field.
func RowidGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldRowid, v))
}

// RowidGTE applies the GTE predicate on the "rowid" field.
func RowidGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldRowid, v))
}

// RowidLT applies the LT predicate on the "rowid" field.
func RowidLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldRowid, v))
}

// RowidLTE applies the LTE predicate on the "rowid" field.
func RowidLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldRowid, v))
}

// RowidIsNil applies the IsNil predicate on the "rowid" field.
func RowidIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldRowid))
}

// RowidNotNil applies the NotNil predicate on the "rowid" field.
func RowidNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldRowid))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldUpdateTime, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldTitle, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldURL, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	return predicate.TaskOrErr(sql.FieldEQ(FieldState, vc), err)
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	return predicate.TaskOrErr(sql.FieldNEQ(FieldState, vc), err)
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...browserv1beta.TaskState) predicate.Task {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.State.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.TaskOrErr(sql.FieldIn(FieldState, v...), err)
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...browserv1beta.TaskState) predicate.Task {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.State.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.TaskOrErr(sql.FieldNotIn(FieldState, v...), err)
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	return predicate.TaskOrErr(sql.FieldGT(FieldState, vc), err)
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	return predicate.TaskOrErr(sql.FieldGTE(FieldState, vc), err)
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	return predicate.TaskOrErr(sql.FieldLT(FieldState, vc), err)
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	return predicate.TaskOrErr(sql.FieldLTE(FieldState, vc), err)
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("state value is not a string: %T", vc)
	}
	return predicate.TaskOrErr(sql.FieldContains(FieldState, vcs), err)
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("state value is not a string: %T", vc)
	}
	return predicate.TaskOrErr(sql.FieldHasPrefix(FieldState, vcs), err)
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("state value is not a string: %T", vc)
	}
	return predicate.TaskOrErr(sql.FieldHasSuffix(FieldState, vcs), err)
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("state value is not a string: %T", vc)
	}
	return predicate.TaskOrErr(sql.FieldEqualFold(FieldState, vcs), err)
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v browserv1beta.TaskState) predicate.Task {
	vc, err := ValueScanner.State.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("state value is not a string: %T", vc)
	}
	return predicate.TaskOrErr(sql.FieldContainsFold(FieldState, vcs), err)
}

// SchemaIDEQ applies the EQ predicate on the "schema_id" field.
func SchemaIDEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldSchemaID, v))
}

// SchemaIDNEQ applies the NEQ predicate on the "schema_id" field.
func SchemaIDNEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldSchemaID, v))
}

// SchemaIDIn applies the In predicate on the "schema_id" field.
func SchemaIDIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldSchemaID, vs...))
}

// SchemaIDNotIn applies the NotIn predicate on the "schema_id" field.
func SchemaIDNotIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldSchemaID, vs...))
}

// SchemaIDIsNil applies the IsNil predicate on the "schema_id" field.
func SchemaIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldSchemaID))
}

// SchemaIDNotNil applies the NotNil predicate on the "schema_id" field.
func SchemaIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldSchemaID))
}

// RecordIDEQ applies the EQ predicate on the "record_id" field.
func RecordIDEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRecordID, v))
}

// RecordIDNEQ applies the NEQ predicate on the "record_id" field.
func RecordIDNEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldRecordID, v))
}

// RecordIDIn applies the In predicate on the "record_id" field.
func RecordIDIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldRecordID, vs...))
}

// RecordIDNotIn applies the NotIn predicate on the "record_id" field.
func RecordIDNotIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldRecordID, vs...))
}

// RecordIDGT applies the GT predicate on the "record_id" field.
func RecordIDGT(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldRecordID, v))
}

// RecordIDGTE applies the GTE predicate on the "record_id" field.
func RecordIDGTE(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldRecordID, v))
}

// RecordIDLT applies the LT predicate on the "record_id" field.
func RecordIDLT(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldRecordID, v))
}

// RecordIDLTE applies the LTE predicate on the "record_id" field.
func RecordIDLTE(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldRecordID, v))
}

// RecordIDIsNil applies the IsNil predicate on the "record_id" field.
func RecordIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldRecordID))
}

// RecordIDNotNil applies the NotNil predicate on the "record_id" field.
func RecordIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldRecordID))
}

// CompleteTimeEQ applies the EQ predicate on the "complete_time" field.
func CompleteTimeEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCompleteTime, v))
}

// CompleteTimeNEQ applies the NEQ predicate on the "complete_time" field.
func CompleteTimeNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCompleteTime, v))
}

// CompleteTimeIn applies the In predicate on the "complete_time" field.
func CompleteTimeIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCompleteTime, vs...))
}

// CompleteTimeNotIn applies the NotIn predicate on the "complete_time" field.
func CompleteTimeNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCompleteTime, vs...))
}

// CompleteTimeGT applies the GT predicate on the "complete_time" field.
func CompleteTimeGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCompleteTime, v))
}

// CompleteTimeGTE applies the GTE predicate on the "complete_time" field.
func CompleteTimeGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCompleteTime, v))
}

// CompleteTimeLT applies the LT predicate on the "complete_time" field.
func CompleteTimeLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCompleteTime, v))
}

// CompleteTimeLTE applies the LTE predicate on the "complete_time" field.
func CompleteTimeLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCompleteTime, v))
}

// CompleteTimeIsNil applies the IsNil predicate on the "complete_time" field.
func CompleteTimeIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldCompleteTime))
}

// CompleteTimeNotNil applies the NotNil predicate on the "complete_time" field.
func CompleteTimeNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldCompleteTime))
}

// ExtensionIDEQ applies the EQ predicate on the "extension_id" field.
func ExtensionIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldExtensionID, v))
}

// ExtensionIDNEQ applies the NEQ predicate on the "extension_id" field.
func ExtensionIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldExtensionID, v))
}

// ExtensionIDIn applies the In predicate on the "extension_id" field.
func ExtensionIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldExtensionID, vs...))
}

// ExtensionIDNotIn applies the NotIn predicate on the "extension_id" field.
func ExtensionIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldExtensionID, vs...))
}

// ExtensionIDGT applies the GT predicate on the "extension_id" field.
func ExtensionIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldExtensionID, v))
}

// ExtensionIDGTE applies the GTE predicate on the "extension_id" field.
func ExtensionIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldExtensionID, v))
}

// ExtensionIDLT applies the LT predicate on the "extension_id" field.
func ExtensionIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldExtensionID, v))
}

// ExtensionIDLTE applies the LTE predicate on the "extension_id" field.
func ExtensionIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldExtensionID, v))
}

// ExtensionIDContains applies the Contains predicate on the "extension_id" field.
func ExtensionIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldExtensionID, v))
}

// ExtensionIDHasPrefix applies the HasPrefix predicate on the "extension_id" field.
func ExtensionIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldExtensionID, v))
}

// ExtensionIDHasSuffix applies the HasSuffix predicate on the "extension_id" field.
func ExtensionIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldExtensionID, v))
}

// ExtensionIDEqualFold applies the EqualFold predicate on the "extension_id" field.
func ExtensionIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldExtensionID, v))
}

// ExtensionIDContainsFold applies the ContainsFold predicate on the "extension_id" field.
func ExtensionIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldExtensionID, v))
}

// HasSchema applies the HasEdge predicate on the "schema" edge.
func HasSchema() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SchemaTable, SchemaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSchemaWith applies the HasEdge predicate on the "schema" edge with a given conditions (other predicates).
func HasSchemaWith(preds ...predicate.ExtractionSchema) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newSchemaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
