apiVersion: v1
kind: Service
metadata:
  name: metabusiness
spec:
  ports:
  - name: http-grpc
    port: 80
    targetPort: http-grpc
---
apiVersion: v1
kind: Service
metadata:
  name: metabusiness-headless
spec:
  clusterIP: None
  ports:
  - name: http-grpc
    port: 9090
    targetPort: http-grpc
