# yaml-language-server: $schema=http://localhost:9900/schemas/dtkt.integrationsdk.v1beta1.Package.jsonschema.json
kind: Package
apiVersion: v1beta1
spec:
  identity:
    name: Email
    version: 0.0.0
  description: |
    Send individual, batched, or streamed emails to any compatible SMTP server and subscribe to email events through POP3 and IMAP.
  icon: https://assets.datakit.cloud/icons/email.svg
  type: PACKAGE_TYPE_GO
  build: {}
