apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: email
build:
  local:
    useBuildkit: true
  artifacts:
  - image: intgr-email
    context: ../../../
    docker:
      dockerfile: dtkt-integrations/packages/email/Dockerfile
manifests:
  kustomize:
    buildArgs:
    - --enable-alpha-plugins
    - --enable-exec
    paths:
    - infra/kustomize/overlays/dev
deploy:
  kubeContext: kind-dtkt-local
  kubectl:
    defaultNamespace: dtkt-integrations
# portForward:
# - resourceType: service
#   resourceName: email
#   port: 80
#   localPort: 8200
