apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels: {}
  template:
    spec:
      serviceAccountName: email
      containers:
      - image: email
        name: email
        env:
        - name: HOST
          value: 0.0.0.0
        envFrom:
        - configMapRef:
            name: email
        ports:
        - containerPort: 9090
          name: http-grpc
        resources:
          requests:
            cpu: 500m
          limits:
            memory: 512Mi
        livenessProbe:
          grpc:
            port: 9090
        readinessProbe:
          grpc:
            port: 9090
