package v1beta1

import (
	"cloud.google.com/go/bigquery"
	"github.com/datakit-dev/dtkt-sdk/sdk-go/integrationsdk/v1beta1"
	sharedv1beta1 "github.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/shared/v1beta1"
)

var Types = v1beta1.NewDataTypes(
	v1beta1.NewDataType(bigquery.BooleanFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_BOOLEAN),
	),
	v1beta1.NewDataType(bigquery.StringFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
	v1beta1.NewDataType(bigquery.BytesFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
	v1beta1.NewDataType(bigquery.IntegerFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_NUMBER),
	),
	v1beta1.NewDataType(bigquery.FloatFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_NUMBER),
	),
	v1beta1.NewDataType(bigquery.NumericFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_NUMBER),
	),
	v1beta1.NewDataType(bigquery.BigNumericFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_NUMBER),
	),
	v1beta1.NewDataType(bigquery.DateFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
	v1beta1.NewDataType(bigquery.DateTimeFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
	v1beta1.NewDataType(bigquery.TimeFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
	v1beta1.NewDataType(bigquery.TimestampFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
	v1beta1.NewDataType(bigquery.JSONFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
	v1beta1.NewDataType(bigquery.RecordFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_OBJECT),
	),
	v1beta1.NewDataType(bigquery.GeographyFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
		v1beta1.WithGeoType(sharedv1beta1.GeoType_GEO_TYPE_JSON),
	),
	v1beta1.NewDataType(bigquery.IntervalFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_NUMBER),
	),
	v1beta1.NewDataType(bigquery.RangeFieldType,
		v1beta1.WithJSONType(sharedv1beta1.JSONType_JSON_TYPE_STRING),
	),
)
