# yaml-language-server: $schema=http://localhost:9900/schemas/dtkt.flowsdk.v1beta1.Flow.jsonschema.json

apiVersion: v1beta1
kind: Flow
spec:
  name: BigQuery Audit Logs
  description: >
    Stream BigQuery audit logs.

  connections:
    - id: catalog
      package:
        name: BigQuery
        version: 0.1.0

  streams:
    - id: auditLogs
      call:
        connection: catalog
        method: dtkt.event.v1beta1.EventService.StreamPullEvents
        request:
          name: "AuditLogs"

  outputs:
    - id: type
      value: = streams.auditLogs.value.event.type
    - id: payload
      value: = streams.auditLogs.value.event.payload
