# yaml-language-server: $schema=http://localhost:9900/schemas/dtkt.flowsdk.v1beta1.Flow.jsonschema.json

apiVersion: v1beta1
kind: Flow
spec:
  name: Catalog Query Streaming Results
  description: >
    Query streaming results from a given CatalogService.

  connections:
    - id: catalog
      services:
        - dtkt.catalog.v1beta1.CatalogService

  actions:
    - id: query
      user:
        inputs:
          - id: value
            title: Enter a query

  streams:
    - id: queryStream
      call:
        connection: catalog
        method: dtkt.catalog.v1beta1.QueryService.StreamQueryResults
        request:
          query: = actions.query.value

  outputs:
    - id: row
      value: = sources.queryStream?.Row
