# yaml-language-server: $schema=http://localhost:9900/schemas/dtkt.flowsdk.v1beta1.Flow.jsonschema.json

apiVersion: v1beta1
kind: Flow
spec:
  name: Create Embeddings
  description: Create embeddings for given input text data.

  connections:
    - id: embedding
      services:
        - dtkt.ai.v1beta1.EmbeddingService

  inputs:
    - id: embeddingInputs
      list:
        items: dtkt.ai.v1beta1.EmbeddingInput
        nullable: false
    - id: embeddingModelId
      string:
        nullable: false
    - id: embeddingDimensions
      uint32:
        nullable: false

  actions:
    - id: createEmbeddings
      call:
        connection: embedding
        method: dtkt.ai.v1beta1.EmbeddingService.GenerateEmbeddings
        request:
          modelId: = inputs.embeddingModelId.value
          dimensions: = inputs.embeddingDimensions.value
          inputs: = inputs.embeddingInputs.value

  outputs:
    - id: embeddings
      value: = actions.createEmbeddings.value
