# yaml-language-server: $schema=http://localhost:9900/schemas/dtkt.flowsdk.v1beta1.Flow.jsonschema.json

apiVersion: v1beta1
kind: Flow
spec:
  name: Fivetran Destination Webhook Events
  description: >
    Stream Fivetran Destination webhook events.

  connections:
    - id: destination
      services:
        - dtkt.replication.v1beta1.DestinationService

  streams:
    - id: webhook
      call:
        connection: destination
        method: dtkt.event.v1beta1.EventService.StreamPushEvents
        request:
          eventSource:
            name: FivetranWebhook

  outputs:
    - id: eventType
      value: = streams.webhook.value.event.type
    - id: eventPayload
      value: = streams.webhook.value.event.paylaod
