# yaml-language-server: $schema=../../dtkt-sdk/schemas/dtkt.flowsdk.v1beta1.Flow.schema.json

apiVersion: v1beta1
kind: Flow
spec:
  name: Fivetran Destination Webhook Events
  description: >
    Stream Fivetran Destination webhook events.

  packages:
    - id: destination
      services:
        - replication.v1beta1.DestinationService

  sources:
    - id: webhook
      call:
        package: destination
        method: event.v1beta1.EventService.StreamPushEvents
        request:
          eventSource:
            name: FivetranWebhook

  outputs:
    - id: eventType
      value: = sources.webhook.Event?.Type
    - id: payload
      value: = sources.webhook.Event?.Payload
