# yaml-language-server: $schema=http://localhost:9900/schemas/dtkt.flowsdk.v1beta1.Flow.jsonschema.json

apiVersion: v1beta1
kind: Flow
spec:
  name: OpenAI Realtime Chat
  description: >
    Chat with an AI assistant in real-time using OpenAI's RealtimeAPI.

  connections:
    - id: openai
      package:
        name: OpenAI
        version: 0.1.0

  inputs:
    - id: realtimeConfig
      message:
        type: google.protobuf.Struct
        default:
          id: foobar
    - id: sessionConfig
      message:
        type: google.protobuf.Struct
        default:
          instructions: Your name is Data and you are an assistant at DataKit, an innovative platform for data activation and workflow automation.
          modalities:
            - text
          voice: coral

  streams:
    - id: realtimeEvents
      call:
        connection: openai
        method: dtkt.event.v1beta1.EventService.StreamPullEvents
        request:
          eventSource:
            name: RealtimeEvents
            config: = inputs.realtimeConfig.value

  vars:
    - id: event
      value: = streams.realtimeEvents.value.event
    - id: eventType
      value: = vars.event.value.type
    - id: eventPayload
      value: = vars.event.value.payload
    - id: assistantMessage
      switch:
        value: = vars.eventType.value
        case:
          - value: = "response.text.done"
            return: = vars.eventPayload.value.text
        default: = null
    - id: userMessage
      switch:
        value: = vars.eventType.value
        case:
          - value: = "conversation.item.created"
            return: = vars.eventPayload.value.item
        default: = null

  actions:
    - id: updateSession
      call:
        connection: openai
        method: dtkt.action.v1beta1.ActionService.ExecuteAction
        invokeWhen: = vars.eventType.value == "session.created"
        request:
          action:
            name: SessionUpdate
          input:
            config: = inputs.realtimeConfig.value
            event:
              type: session.update
              session: = inputs.sessionConfig.value

    # - id: userMessage
    #   user:
    #     inputs:
    #       - id: text
    #         title: Enter a message
    #         input:
    #           multilineText: true

    - id: sendMessage
      call:
        connection: openai
        method: dtkt.action.v1beta1.ActionService.ExecuteAction
        invokeWhen: = vars.eventType.value == "response.done"
        request:
          action:
            name: ConversationItemCreate
          input:
            config: = inputs.realtimeConfig.value
            event:
              type: conversation.item.create
              item:
                type: message
                role: user
                # content:
                #   - type: input_text
                #     text: = actions.userMessage.value.text

    - id: createResponse
      call:
        connection: openai
        method: dtkt.action.v1beta1.ActionService.ExecuteAction
        invokeWhen: = vars.eventType.value == "session.updated" || actions.sendMessage.value != null
        request:
          action:
            name: ResponseCreate
          input:
            config: = inputs.realtimeConfig.value
            event:
              type: response.create

  outputs:
    - id: assistant
      value: = vars.assistantMessage.value
    # - id: user
    #   value: = vars.userMessage.value
