apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: command
profiles:
- name: command
  build:
    local:
      useBuildkit: true
    artifacts:
    - image: intgr-command
      context: ../../../
      docker:
        dockerfile: dtkt-integrations/packages/command/Dockerfile
  manifests:
    kustomize:
      buildArgs:
      - --enable-alpha-plugins
      - --enable-exec
      paths:
      - infra/kustomize/overlays/dev
  deploy:
    kubeContext: kind-dtkt-local
    kubectl:
      defaultNamespace: dtkt-integrations
  # portForward:
  # - resourceType: service
  #   resourceName: command
  #   port: 80
  #   localPort: 8200
