// Code generated by ent, DO NOT EDIT.

package extractionschema

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datakit-dev/dtkt-integrations/browser/pkg/db/ent/predicate"
	browserv1beta "github.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLTE(FieldID, id))
}

// Rowid applies equality check predicate on the "rowid" field. It's identical to RowidEQ.
func Rowid(v int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldRowid, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldUpdateTime, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldDescription, v))
}

// Fields applies equality check predicate on the "fields" field. It's identical to FieldsEQ.
func Fields(v []*browserv1beta.FieldDef) predicate.ExtractionSchema {
	vc, err := ValueScanner.Fields.Value(v)
	return predicate.ExtractionSchemaOrErr(sql.FieldEQ(FieldFields, vc), err)
}

// ExtensionID applies equality check predicate on the "extension_id" field. It's identical to ExtensionIDEQ.
func ExtensionID(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldExtensionID, v))
}

// RowidEQ applies the EQ predicate on the "rowid" field.
func RowidEQ(v int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldRowid, v))
}

// RowidNEQ applies the NEQ predicate on the "rowid" field.
func RowidNEQ(v int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNEQ(FieldRowid, v))
}

// RowidIn applies the In predicate on the "rowid" field.
func RowidIn(vs ...int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIn(FieldRowid, vs...))
}

// RowidNotIn applies the NotIn predicate on the "rowid" field.
func RowidNotIn(vs ...int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotIn(FieldRowid, vs...))
}

// RowidGT applies the GT predicate on the "rowid" field.
func RowidGT(v int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGT(FieldRowid, v))
}

// RowidGTE applies the GTE predicate on the "rowid" field.
func RowidGTE(v int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGTE(FieldRowid, v))
}

// RowidLT applies the LT predicate on the "rowid" field.
func RowidLT(v int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLT(FieldRowid, v))
}

// RowidLTE applies the LTE predicate on the "rowid" field.
func RowidLTE(v int64) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLTE(FieldRowid, v))
}

// RowidIsNil applies the IsNil predicate on the "rowid" field.
func RowidIsNil() predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIsNull(FieldRowid))
}

// RowidNotNil applies the NotNil predicate on the "rowid" field.
func RowidNotNil() predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotNull(FieldRowid))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLTE(FieldUpdateTime, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldContainsFold(FieldDescription, v))
}

// FieldsEQ applies the EQ predicate on the "fields" field.
func FieldsEQ(v []*browserv1beta.FieldDef) predicate.ExtractionSchema {
	vc, err := ValueScanner.Fields.Value(v)
	return predicate.ExtractionSchemaOrErr(sql.FieldEQ(FieldFields, vc), err)
}

// FieldsNEQ applies the NEQ predicate on the "fields" field.
func FieldsNEQ(v []*browserv1beta.FieldDef) predicate.ExtractionSchema {
	vc, err := ValueScanner.Fields.Value(v)
	return predicate.ExtractionSchemaOrErr(sql.FieldNEQ(FieldFields, vc), err)
}

// FieldsIn applies the In predicate on the "fields" field.
func FieldsIn(vs ...[]*browserv1beta.FieldDef) predicate.ExtractionSchema {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Fields.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.ExtractionSchemaOrErr(sql.FieldIn(FieldFields, v...), err)
}

// FieldsNotIn applies the NotIn predicate on the "fields" field.
func FieldsNotIn(vs ...[]*browserv1beta.FieldDef) predicate.ExtractionSchema {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Fields.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.ExtractionSchemaOrErr(sql.FieldNotIn(FieldFields, v...), err)
}

// FieldsGT applies the GT predicate on the "fields" field.
func FieldsGT(v []*browserv1beta.FieldDef) predicate.ExtractionSchema {
	vc, err := ValueScanner.Fields.Value(v)
	return predicate.ExtractionSchemaOrErr(sql.FieldGT(FieldFields, vc), err)
}

// FieldsGTE applies the GTE predicate on the "fields" field.
func FieldsGTE(v []*browserv1beta.FieldDef) predicate.ExtractionSchema {
	vc, err := ValueScanner.Fields.Value(v)
	return predicate.ExtractionSchemaOrErr(sql.FieldGTE(FieldFields, vc), err)
}

// FieldsLT applies the LT predicate on the "fields" field.
func FieldsLT(v []*browserv1beta.FieldDef) predicate.ExtractionSchema {
	vc, err := ValueScanner.Fields.Value(v)
	return predicate.ExtractionSchemaOrErr(sql.FieldLT(FieldFields, vc), err)
}

// FieldsLTE applies the LTE predicate on the "fields" field.
func FieldsLTE(v []*browserv1beta.FieldDef) predicate.ExtractionSchema {
	vc, err := ValueScanner.Fields.Value(v)
	return predicate.ExtractionSchemaOrErr(sql.FieldLTE(FieldFields, vc), err)
}

// ExtensionIDEQ applies the EQ predicate on the "extension_id" field.
func ExtensionIDEQ(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEQ(FieldExtensionID, v))
}

// ExtensionIDNEQ applies the NEQ predicate on the "extension_id" field.
func ExtensionIDNEQ(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNEQ(FieldExtensionID, v))
}

// ExtensionIDIn applies the In predicate on the "extension_id" field.
func ExtensionIDIn(vs ...string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldIn(FieldExtensionID, vs...))
}

// ExtensionIDNotIn applies the NotIn predicate on the "extension_id" field.
func ExtensionIDNotIn(vs ...string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldNotIn(FieldExtensionID, vs...))
}

// ExtensionIDGT applies the GT predicate on the "extension_id" field.
func ExtensionIDGT(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGT(FieldExtensionID, v))
}

// ExtensionIDGTE applies the GTE predicate on the "extension_id" field.
func ExtensionIDGTE(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldGTE(FieldExtensionID, v))
}

// ExtensionIDLT applies the LT predicate on the "extension_id" field.
func ExtensionIDLT(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLT(FieldExtensionID, v))
}

// ExtensionIDLTE applies the LTE predicate on the "extension_id" field.
func ExtensionIDLTE(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldLTE(FieldExtensionID, v))
}

// ExtensionIDContains applies the Contains predicate on the "extension_id" field.
func ExtensionIDContains(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldContains(FieldExtensionID, v))
}

// ExtensionIDHasPrefix applies the HasPrefix predicate on the "extension_id" field.
func ExtensionIDHasPrefix(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldHasPrefix(FieldExtensionID, v))
}

// ExtensionIDHasSuffix applies the HasSuffix predicate on the "extension_id" field.
func ExtensionIDHasSuffix(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldHasSuffix(FieldExtensionID, v))
}

// ExtensionIDEqualFold applies the EqualFold predicate on the "extension_id" field.
func ExtensionIDEqualFold(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldEqualFold(FieldExtensionID, v))
}

// ExtensionIDContainsFold applies the ContainsFold predicate on the "extension_id" field.
func ExtensionIDContainsFold(v string) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.FieldContainsFold(FieldExtensionID, v))
}

// HasRecords applies the HasEdge predicate on the "records" edge.
func HasRecords() predicate.ExtractionSchema {
	return predicate.ExtractionSchema(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecordsTable, RecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordsWith applies the HasEdge predicate on the "records" edge with a given conditions (other predicates).
func HasRecordsWith(preds ...predicate.ExtractionRecord) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(func(s *sql.Selector) {
		step := newRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.ExtractionSchema {
	return predicate.ExtractionSchema(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.Task) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExtractionSchema) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExtractionSchema) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExtractionSchema) predicate.ExtractionSchema {
	return predicate.ExtractionSchema(sql.NotPredicates(p))
}
