// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: integration/browser/v1beta/config.proto

package browserv1beta

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Browser:
	//
	//	*Config_Chrome
	Browser       isConfig_Browser `protobuf_oneof:"browser"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_integration_browser_v1beta_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetBrowser() isConfig_Browser {
	if x != nil {
		return x.Browser
	}
	return nil
}

func (x *Config) GetChrome() *ChromeConfig {
	if x != nil {
		if x, ok := x.Browser.(*Config_Chrome); ok {
			return x.Chrome
		}
	}
	return nil
}

type isConfig_Browser interface {
	isConfig_Browser()
}

type Config_Chrome struct {
	Chrome *ChromeConfig `protobuf:"bytes,1,opt,name=chrome,proto3,oneof"`
}

func (*Config_Chrome) isConfig_Browser() {}

var File_integration_browser_v1beta_config_proto protoreflect.FileDescriptor

const file_integration_browser_v1beta_config_proto_rawDesc = "" +
	"\n" +
	"'integration/browser/v1beta/config.proto\x12\x1aintegration.browser.v1beta\x1a\x1bbuf/validate/validate.proto\x1a'integration/browser/v1beta/chrome.proto\"^\n" +
	"\x06Config\x12B\n" +
	"\x06chrome\x18\x01 \x01(\v2(.integration.browser.v1beta.ChromeConfigH\x00R\x06chromeB\x10\n" +
	"\abrowser\x12\x05\xbaH\x02\b\x01B\x9c\x02\n" +
	"\x1ecom.integration.browser.v1betaB\vConfigProtoP\x01Zcgithub.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta;browserv1beta\xa2\x02\x03IBX\xaa\x02\x1aIntegration.Browser.V1beta\xca\x02\x1aIntegration\\Browser\\V1beta\xe2\x02&Integration\\Browser\\V1beta\\GPBMetadata\xea\x02\x1cIntegration::Browser::V1betab\x06proto3"

var (
	file_integration_browser_v1beta_config_proto_rawDescOnce sync.Once
	file_integration_browser_v1beta_config_proto_rawDescData []byte
)

func file_integration_browser_v1beta_config_proto_rawDescGZIP() []byte {
	file_integration_browser_v1beta_config_proto_rawDescOnce.Do(func() {
		file_integration_browser_v1beta_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_browser_v1beta_config_proto_rawDesc), len(file_integration_browser_v1beta_config_proto_rawDesc)))
	})
	return file_integration_browser_v1beta_config_proto_rawDescData
}

var file_integration_browser_v1beta_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_integration_browser_v1beta_config_proto_goTypes = []any{
	(*Config)(nil),       // 0: integration.browser.v1beta.Config
	(*ChromeConfig)(nil), // 1: integration.browser.v1beta.ChromeConfig
}
var file_integration_browser_v1beta_config_proto_depIdxs = []int32{
	1, // 0: integration.browser.v1beta.Config.chrome:type_name -> integration.browser.v1beta.ChromeConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_integration_browser_v1beta_config_proto_init() }
func file_integration_browser_v1beta_config_proto_init() {
	if File_integration_browser_v1beta_config_proto != nil {
		return
	}
	file_integration_browser_v1beta_chrome_proto_init()
	file_integration_browser_v1beta_config_proto_msgTypes[0].OneofWrappers = []any{
		(*Config_Chrome)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_browser_v1beta_config_proto_rawDesc), len(file_integration_browser_v1beta_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integration_browser_v1beta_config_proto_goTypes,
		DependencyIndexes: file_integration_browser_v1beta_config_proto_depIdxs,
		MessageInfos:      file_integration_browser_v1beta_config_proto_msgTypes,
	}.Build()
	File_integration_browser_v1beta_config_proto = out.File
	file_integration_browser_v1beta_config_proto_goTypes = nil
	file_integration_browser_v1beta_config_proto_depIdxs = nil
}
