// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: integration/browser/v1beta/context.proto

package browserv1beta

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Connection    string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_integration_browser_v1beta_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_context_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Context) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

var File_integration_browser_v1beta_context_proto protoreflect.FileDescriptor

const file_integration_browser_v1beta_context_proto_rawDesc = "" +
	"\n" +
	"(integration/browser/v1beta/context.proto\x12\x1aintegration.browser.v1beta\x1a\x1bbuf/validate/validate.proto\"X\n" +
	"\aContext\x12%\n" +
	"\aaddress\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x88\x01\x01R\aaddress\x12&\n" +
	"\n" +
	"connection\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"connectionB\x9d\x02\n" +
	"\x1ecom.integration.browser.v1betaB\fContextProtoP\x01Zcgithub.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta;browserv1beta\xa2\x02\x03IBX\xaa\x02\x1aIntegration.Browser.V1beta\xca\x02\x1aIntegration\\Browser\\V1beta\xe2\x02&Integration\\Browser\\V1beta\\GPBMetadata\xea\x02\x1cIntegration::Browser::V1betab\x06proto3"

var (
	file_integration_browser_v1beta_context_proto_rawDescOnce sync.Once
	file_integration_browser_v1beta_context_proto_rawDescData []byte
)

func file_integration_browser_v1beta_context_proto_rawDescGZIP() []byte {
	file_integration_browser_v1beta_context_proto_rawDescOnce.Do(func() {
		file_integration_browser_v1beta_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_browser_v1beta_context_proto_rawDesc), len(file_integration_browser_v1beta_context_proto_rawDesc)))
	})
	return file_integration_browser_v1beta_context_proto_rawDescData
}

var file_integration_browser_v1beta_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_integration_browser_v1beta_context_proto_goTypes = []any{
	(*Context)(nil), // 0: integration.browser.v1beta.Context
}
var file_integration_browser_v1beta_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_integration_browser_v1beta_context_proto_init() }
func file_integration_browser_v1beta_context_proto_init() {
	if File_integration_browser_v1beta_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_browser_v1beta_context_proto_rawDesc), len(file_integration_browser_v1beta_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integration_browser_v1beta_context_proto_goTypes,
		DependencyIndexes: file_integration_browser_v1beta_context_proto_depIdxs,
		MessageInfos:      file_integration_browser_v1beta_context_proto_msgTypes,
	}.Build()
	File_integration_browser_v1beta_context_proto = out.File
	file_integration_browser_v1beta_context_proto_goTypes = nil
	file_integration_browser_v1beta_context_proto_depIdxs = nil
}
