// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: integration/browser/v1beta/extraction.proto

package browserv1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtractionSchemaService_CreateExtractionSchema_FullMethodName = "/integration.browser.v1beta.ExtractionSchemaService/CreateExtractionSchema"
	ExtractionSchemaService_GetExtractionSchema_FullMethodName    = "/integration.browser.v1beta.ExtractionSchemaService/GetExtractionSchema"
	ExtractionSchemaService_ListExtractionSchemas_FullMethodName  = "/integration.browser.v1beta.ExtractionSchemaService/ListExtractionSchemas"
	ExtractionSchemaService_UpdateExtractionSchema_FullMethodName = "/integration.browser.v1beta.ExtractionSchemaService/UpdateExtractionSchema"
	ExtractionSchemaService_DeleteExtractionSchema_FullMethodName = "/integration.browser.v1beta.ExtractionSchemaService/DeleteExtractionSchema"
)

// ExtractionSchemaServiceClient is the client API for ExtractionSchemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExtractionSchemaService manages reusable field-definition sets used to
// configure Data Extraction tasks. Schemas are created once and referenced by
// many tasks rather than embedding field definitions per-task.
type ExtractionSchemaServiceClient interface {
	// Create a new extraction schema.
	CreateExtractionSchema(ctx context.Context, in *CreateExtractionSchemaRequest, opts ...grpc.CallOption) (*CreateExtractionSchemaResponse, error)
	// Get a single schema by ID.
	GetExtractionSchema(ctx context.Context, in *GetExtractionSchemaRequest, opts ...grpc.CallOption) (*GetExtractionSchemaResponse, error)
	// List schemas, with optional name filter.
	ListExtractionSchemas(ctx context.Context, in *ListExtractionSchemasRequest, opts ...grpc.CallOption) (*ListExtractionSchemasResponse, error)
	// Update a schema (e.g. add/rename fields).
	UpdateExtractionSchema(ctx context.Context, in *UpdateExtractionSchemaRequest, opts ...grpc.CallOption) (*UpdateExtractionSchemaResponse, error)
	// Delete a schema. Tasks referencing it are not affected.
	DeleteExtractionSchema(ctx context.Context, in *DeleteExtractionSchemaRequest, opts ...grpc.CallOption) (*DeleteExtractionSchemaResponse, error)
}

type extractionSchemaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractionSchemaServiceClient(cc grpc.ClientConnInterface) ExtractionSchemaServiceClient {
	return &extractionSchemaServiceClient{cc}
}

func (c *extractionSchemaServiceClient) CreateExtractionSchema(ctx context.Context, in *CreateExtractionSchemaRequest, opts ...grpc.CallOption) (*CreateExtractionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExtractionSchemaResponse)
	err := c.cc.Invoke(ctx, ExtractionSchemaService_CreateExtractionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionSchemaServiceClient) GetExtractionSchema(ctx context.Context, in *GetExtractionSchemaRequest, opts ...grpc.CallOption) (*GetExtractionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractionSchemaResponse)
	err := c.cc.Invoke(ctx, ExtractionSchemaService_GetExtractionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionSchemaServiceClient) ListExtractionSchemas(ctx context.Context, in *ListExtractionSchemasRequest, opts ...grpc.CallOption) (*ListExtractionSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExtractionSchemasResponse)
	err := c.cc.Invoke(ctx, ExtractionSchemaService_ListExtractionSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionSchemaServiceClient) UpdateExtractionSchema(ctx context.Context, in *UpdateExtractionSchemaRequest, opts ...grpc.CallOption) (*UpdateExtractionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateExtractionSchemaResponse)
	err := c.cc.Invoke(ctx, ExtractionSchemaService_UpdateExtractionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionSchemaServiceClient) DeleteExtractionSchema(ctx context.Context, in *DeleteExtractionSchemaRequest, opts ...grpc.CallOption) (*DeleteExtractionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExtractionSchemaResponse)
	err := c.cc.Invoke(ctx, ExtractionSchemaService_DeleteExtractionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractionSchemaServiceServer is the server API for ExtractionSchemaService service.
// All implementations must embed UnimplementedExtractionSchemaServiceServer
// for forward compatibility.
//
// ExtractionSchemaService manages reusable field-definition sets used to
// configure Data Extraction tasks. Schemas are created once and referenced by
// many tasks rather than embedding field definitions per-task.
type ExtractionSchemaServiceServer interface {
	// Create a new extraction schema.
	CreateExtractionSchema(context.Context, *CreateExtractionSchemaRequest) (*CreateExtractionSchemaResponse, error)
	// Get a single schema by ID.
	GetExtractionSchema(context.Context, *GetExtractionSchemaRequest) (*GetExtractionSchemaResponse, error)
	// List schemas, with optional name filter.
	ListExtractionSchemas(context.Context, *ListExtractionSchemasRequest) (*ListExtractionSchemasResponse, error)
	// Update a schema (e.g. add/rename fields).
	UpdateExtractionSchema(context.Context, *UpdateExtractionSchemaRequest) (*UpdateExtractionSchemaResponse, error)
	// Delete a schema. Tasks referencing it are not affected.
	DeleteExtractionSchema(context.Context, *DeleteExtractionSchemaRequest) (*DeleteExtractionSchemaResponse, error)
	mustEmbedUnimplementedExtractionSchemaServiceServer()
}

// UnimplementedExtractionSchemaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtractionSchemaServiceServer struct{}

func (UnimplementedExtractionSchemaServiceServer) CreateExtractionSchema(context.Context, *CreateExtractionSchemaRequest) (*CreateExtractionSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExtractionSchema not implemented")
}
func (UnimplementedExtractionSchemaServiceServer) GetExtractionSchema(context.Context, *GetExtractionSchemaRequest) (*GetExtractionSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExtractionSchema not implemented")
}
func (UnimplementedExtractionSchemaServiceServer) ListExtractionSchemas(context.Context, *ListExtractionSchemasRequest) (*ListExtractionSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExtractionSchemas not implemented")
}
func (UnimplementedExtractionSchemaServiceServer) UpdateExtractionSchema(context.Context, *UpdateExtractionSchemaRequest) (*UpdateExtractionSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExtractionSchema not implemented")
}
func (UnimplementedExtractionSchemaServiceServer) DeleteExtractionSchema(context.Context, *DeleteExtractionSchemaRequest) (*DeleteExtractionSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExtractionSchema not implemented")
}
func (UnimplementedExtractionSchemaServiceServer) mustEmbedUnimplementedExtractionSchemaServiceServer() {
}
func (UnimplementedExtractionSchemaServiceServer) testEmbeddedByValue() {}

// UnsafeExtractionSchemaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractionSchemaServiceServer will
// result in compilation errors.
type UnsafeExtractionSchemaServiceServer interface {
	mustEmbedUnimplementedExtractionSchemaServiceServer()
}

func RegisterExtractionSchemaServiceServer(s grpc.ServiceRegistrar, srv ExtractionSchemaServiceServer) {
	// If the following call panics, it indicates UnimplementedExtractionSchemaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtractionSchemaService_ServiceDesc, srv)
}

func _ExtractionSchemaService_CreateExtractionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExtractionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionSchemaServiceServer).CreateExtractionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionSchemaService_CreateExtractionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionSchemaServiceServer).CreateExtractionSchema(ctx, req.(*CreateExtractionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionSchemaService_GetExtractionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionSchemaServiceServer).GetExtractionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionSchemaService_GetExtractionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionSchemaServiceServer).GetExtractionSchema(ctx, req.(*GetExtractionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionSchemaService_ListExtractionSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExtractionSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionSchemaServiceServer).ListExtractionSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionSchemaService_ListExtractionSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionSchemaServiceServer).ListExtractionSchemas(ctx, req.(*ListExtractionSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionSchemaService_UpdateExtractionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExtractionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionSchemaServiceServer).UpdateExtractionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionSchemaService_UpdateExtractionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionSchemaServiceServer).UpdateExtractionSchema(ctx, req.(*UpdateExtractionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionSchemaService_DeleteExtractionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExtractionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionSchemaServiceServer).DeleteExtractionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionSchemaService_DeleteExtractionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionSchemaServiceServer).DeleteExtractionSchema(ctx, req.(*DeleteExtractionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtractionSchemaService_ServiceDesc is the grpc.ServiceDesc for ExtractionSchemaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtractionSchemaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integration.browser.v1beta.ExtractionSchemaService",
	HandlerType: (*ExtractionSchemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExtractionSchema",
			Handler:    _ExtractionSchemaService_CreateExtractionSchema_Handler,
		},
		{
			MethodName: "GetExtractionSchema",
			Handler:    _ExtractionSchemaService_GetExtractionSchema_Handler,
		},
		{
			MethodName: "ListExtractionSchemas",
			Handler:    _ExtractionSchemaService_ListExtractionSchemas_Handler,
		},
		{
			MethodName: "UpdateExtractionSchema",
			Handler:    _ExtractionSchemaService_UpdateExtractionSchema_Handler,
		},
		{
			MethodName: "DeleteExtractionSchema",
			Handler:    _ExtractionSchemaService_DeleteExtractionSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integration/browser/v1beta/extraction.proto",
}

const (
	ExtractionRecordService_GetExtractionRecord_FullMethodName    = "/integration.browser.v1beta.ExtractionRecordService/GetExtractionRecord"
	ExtractionRecordService_ListExtractionRecords_FullMethodName  = "/integration.browser.v1beta.ExtractionRecordService/ListExtractionRecords"
	ExtractionRecordService_CreateExtractionRecord_FullMethodName = "/integration.browser.v1beta.ExtractionRecordService/CreateExtractionRecord"
	ExtractionRecordService_UpdateExtractionRecord_FullMethodName = "/integration.browser.v1beta.ExtractionRecordService/UpdateExtractionRecord"
	ExtractionRecordService_DeleteExtractionRecord_FullMethodName = "/integration.browser.v1beta.ExtractionRecordService/DeleteExtractionRecord"
)

// ExtractionRecordServiceClient is the client API for ExtractionRecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExtractionRecordService manages the captured value sets produced when
// extraction tasks run. One record is created per task run.
type ExtractionRecordServiceClient interface {
	// Get a single record by ID.
	GetExtractionRecord(ctx context.Context, in *GetExtractionRecordRequest, opts ...grpc.CallOption) (*GetExtractionRecordResponse, error)
	// List all records, optionally filtered by schema or task.
	ListExtractionRecords(ctx context.Context, in *ListExtractionRecordsRequest, opts ...grpc.CallOption) (*ListExtractionRecordsResponse, error)
	// Create a new record. Called by the extension background on first field save.
	CreateExtractionRecord(ctx context.Context, in *CreateExtractionRecordRequest, opts ...grpc.CallOption) (*CreateExtractionRecordResponse, error)
	// Update a record (incremental field saves or final submission).
	UpdateExtractionRecord(ctx context.Context, in *UpdateExtractionRecordRequest, opts ...grpc.CallOption) (*UpdateExtractionRecordResponse, error)
	// Delete a record.
	DeleteExtractionRecord(ctx context.Context, in *DeleteExtractionRecordRequest, opts ...grpc.CallOption) (*DeleteExtractionRecordResponse, error)
}

type extractionRecordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractionRecordServiceClient(cc grpc.ClientConnInterface) ExtractionRecordServiceClient {
	return &extractionRecordServiceClient{cc}
}

func (c *extractionRecordServiceClient) GetExtractionRecord(ctx context.Context, in *GetExtractionRecordRequest, opts ...grpc.CallOption) (*GetExtractionRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractionRecordResponse)
	err := c.cc.Invoke(ctx, ExtractionRecordService_GetExtractionRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionRecordServiceClient) ListExtractionRecords(ctx context.Context, in *ListExtractionRecordsRequest, opts ...grpc.CallOption) (*ListExtractionRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExtractionRecordsResponse)
	err := c.cc.Invoke(ctx, ExtractionRecordService_ListExtractionRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionRecordServiceClient) CreateExtractionRecord(ctx context.Context, in *CreateExtractionRecordRequest, opts ...grpc.CallOption) (*CreateExtractionRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExtractionRecordResponse)
	err := c.cc.Invoke(ctx, ExtractionRecordService_CreateExtractionRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionRecordServiceClient) UpdateExtractionRecord(ctx context.Context, in *UpdateExtractionRecordRequest, opts ...grpc.CallOption) (*UpdateExtractionRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateExtractionRecordResponse)
	err := c.cc.Invoke(ctx, ExtractionRecordService_UpdateExtractionRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionRecordServiceClient) DeleteExtractionRecord(ctx context.Context, in *DeleteExtractionRecordRequest, opts ...grpc.CallOption) (*DeleteExtractionRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExtractionRecordResponse)
	err := c.cc.Invoke(ctx, ExtractionRecordService_DeleteExtractionRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractionRecordServiceServer is the server API for ExtractionRecordService service.
// All implementations must embed UnimplementedExtractionRecordServiceServer
// for forward compatibility.
//
// ExtractionRecordService manages the captured value sets produced when
// extraction tasks run. One record is created per task run.
type ExtractionRecordServiceServer interface {
	// Get a single record by ID.
	GetExtractionRecord(context.Context, *GetExtractionRecordRequest) (*GetExtractionRecordResponse, error)
	// List all records, optionally filtered by schema or task.
	ListExtractionRecords(context.Context, *ListExtractionRecordsRequest) (*ListExtractionRecordsResponse, error)
	// Create a new record. Called by the extension background on first field save.
	CreateExtractionRecord(context.Context, *CreateExtractionRecordRequest) (*CreateExtractionRecordResponse, error)
	// Update a record (incremental field saves or final submission).
	UpdateExtractionRecord(context.Context, *UpdateExtractionRecordRequest) (*UpdateExtractionRecordResponse, error)
	// Delete a record.
	DeleteExtractionRecord(context.Context, *DeleteExtractionRecordRequest) (*DeleteExtractionRecordResponse, error)
	mustEmbedUnimplementedExtractionRecordServiceServer()
}

// UnimplementedExtractionRecordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtractionRecordServiceServer struct{}

func (UnimplementedExtractionRecordServiceServer) GetExtractionRecord(context.Context, *GetExtractionRecordRequest) (*GetExtractionRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExtractionRecord not implemented")
}
func (UnimplementedExtractionRecordServiceServer) ListExtractionRecords(context.Context, *ListExtractionRecordsRequest) (*ListExtractionRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExtractionRecords not implemented")
}
func (UnimplementedExtractionRecordServiceServer) CreateExtractionRecord(context.Context, *CreateExtractionRecordRequest) (*CreateExtractionRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExtractionRecord not implemented")
}
func (UnimplementedExtractionRecordServiceServer) UpdateExtractionRecord(context.Context, *UpdateExtractionRecordRequest) (*UpdateExtractionRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExtractionRecord not implemented")
}
func (UnimplementedExtractionRecordServiceServer) DeleteExtractionRecord(context.Context, *DeleteExtractionRecordRequest) (*DeleteExtractionRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExtractionRecord not implemented")
}
func (UnimplementedExtractionRecordServiceServer) mustEmbedUnimplementedExtractionRecordServiceServer() {
}
func (UnimplementedExtractionRecordServiceServer) testEmbeddedByValue() {}

// UnsafeExtractionRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractionRecordServiceServer will
// result in compilation errors.
type UnsafeExtractionRecordServiceServer interface {
	mustEmbedUnimplementedExtractionRecordServiceServer()
}

func RegisterExtractionRecordServiceServer(s grpc.ServiceRegistrar, srv ExtractionRecordServiceServer) {
	// If the following call panics, it indicates UnimplementedExtractionRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtractionRecordService_ServiceDesc, srv)
}

func _ExtractionRecordService_GetExtractionRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractionRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionRecordServiceServer).GetExtractionRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionRecordService_GetExtractionRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionRecordServiceServer).GetExtractionRecord(ctx, req.(*GetExtractionRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionRecordService_ListExtractionRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExtractionRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionRecordServiceServer).ListExtractionRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionRecordService_ListExtractionRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionRecordServiceServer).ListExtractionRecords(ctx, req.(*ListExtractionRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionRecordService_CreateExtractionRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExtractionRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionRecordServiceServer).CreateExtractionRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionRecordService_CreateExtractionRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionRecordServiceServer).CreateExtractionRecord(ctx, req.(*CreateExtractionRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionRecordService_UpdateExtractionRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExtractionRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionRecordServiceServer).UpdateExtractionRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionRecordService_UpdateExtractionRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionRecordServiceServer).UpdateExtractionRecord(ctx, req.(*UpdateExtractionRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionRecordService_DeleteExtractionRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExtractionRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionRecordServiceServer).DeleteExtractionRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionRecordService_DeleteExtractionRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionRecordServiceServer).DeleteExtractionRecord(ctx, req.(*DeleteExtractionRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtractionRecordService_ServiceDesc is the grpc.ServiceDesc for ExtractionRecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtractionRecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integration.browser.v1beta.ExtractionRecordService",
	HandlerType: (*ExtractionRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExtractionRecord",
			Handler:    _ExtractionRecordService_GetExtractionRecord_Handler,
		},
		{
			MethodName: "ListExtractionRecords",
			Handler:    _ExtractionRecordService_ListExtractionRecords_Handler,
		},
		{
			MethodName: "CreateExtractionRecord",
			Handler:    _ExtractionRecordService_CreateExtractionRecord_Handler,
		},
		{
			MethodName: "UpdateExtractionRecord",
			Handler:    _ExtractionRecordService_UpdateExtractionRecord_Handler,
		},
		{
			MethodName: "DeleteExtractionRecord",
			Handler:    _ExtractionRecordService_DeleteExtractionRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integration/browser/v1beta/extraction.proto",
}
