// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: integration/browser/v1beta/extraction.proto

package browserv1beta

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/protoform/v1beta1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A named field to be captured during task execution.
type FieldDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field identifier, unique within the schema.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable field description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Field value type.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Field value optionality.
	Optional bool `protobuf:"varint,4,opt,name=optional,proto3" json:"optional,omitempty"`
	// Field default value.
	Default       *structpb.Value `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDef) Reset() {
	*x = FieldDef{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDef) ProtoMessage() {}

func (x *FieldDef) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDef.ProtoReflect.Descriptor instead.
func (*FieldDef) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{0}
}

func (x *FieldDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldDef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldDef) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *FieldDef) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

// DOM location metadata captured at pick-time. Stored alongside values to
// enable auto-location on future runs with the same schema on the same domain.
type ElementCapture struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CSS selector path, preferring stable attributes (id, aria-label, data-*).
	CssSelector string `protobuf:"bytes,1,opt,name=css_selector,json=cssSelector,proto3" json:"css_selector,omitempty"`
	// Absolute XPath to the source element.
	Xpath         string `protobuf:"bytes,2,opt,name=xpath,proto3" json:"xpath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementCapture) Reset() {
	*x = ElementCapture{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementCapture) ProtoMessage() {}

func (x *ElementCapture) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementCapture.ProtoReflect.Descriptor instead.
func (*ElementCapture) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{1}
}

func (x *ElementCapture) GetCssSelector() string {
	if x != nil {
		return x.CssSelector
	}
	return ""
}

func (x *ElementCapture) GetXpath() string {
	if x != nil {
		return x.Xpath
	}
	return ""
}

// A named, reusable set of FieldDefs. Multiple tasks can share a schema,
// eliminating repeated field definition at task-creation time.
type ExtractionSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name, e.g. "LinkedIn Profile", "Product Page".
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description explaining the schema's purpose.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Ordered list of fields to capture. At least one is required.
	Fields []*FieldDef `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	// Schema creation time (server-assigned).
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Last update time (server-assigned).
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractionSchema) Reset() {
	*x = ExtractionSchema{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractionSchema) ProtoMessage() {}

func (x *ExtractionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractionSchema.ProtoReflect.Descriptor instead.
func (*ExtractionSchema) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractionSchema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtractionSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtractionSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtractionSchema) GetFields() []*FieldDef {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ExtractionSchema) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ExtractionSchema) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// A single instance of captured data conforming to an ExtractionSchema.
// One record is produced per task run; values are populated incrementally
// as the user picks fields in the overlay, then finalized on submission.
type ExtractionRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The schema this record conforms to.
	SchemaId string `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// The task that produced this record.
	TaskId string `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Captured values keyed by FieldDef.name. Populated incrementally.
	Values map[string]*structpb.Value `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// DOM selector metadata keyed by FieldDef.name. Stored for replay on future runs.
	Captures map[string]*ElementCapture `protobuf:"bytes,5,rep,name=captures,proto3" json:"captures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Record creation time (server-assigned).
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Last update time (server-assigned).
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractionRecord) Reset() {
	*x = ExtractionRecord{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractionRecord) ProtoMessage() {}

func (x *ExtractionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractionRecord.ProtoReflect.Descriptor instead.
func (*ExtractionRecord) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractionRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtractionRecord) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ExtractionRecord) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExtractionRecord) GetValues() map[string]*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ExtractionRecord) GetCaptures() map[string]*ElementCapture {
	if x != nil {
		return x.Captures
	}
	return nil
}

func (x *ExtractionRecord) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ExtractionRecord) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Extraction-specific payload embedded in a Task. Thin reference — the full
// field definitions live in ExtractionSchema and captured values in ExtractionRecord.
type ExtractionTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The schema defining which fields to capture.
	SchemaId string `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// Set once the extension creates an ExtractionRecord for this task run.
	// Empty until the first field value is saved.
	RecordId      string `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractionTask) Reset() {
	*x = ExtractionTask{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractionTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractionTask) ProtoMessage() {}

func (x *ExtractionTask) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractionTask.ProtoReflect.Descriptor instead.
func (*ExtractionTask) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{4}
}

func (x *ExtractionTask) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ExtractionTask) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type CreateExtractionSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *ExtractionSchema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExtractionSchemaRequest) Reset() {
	*x = CreateExtractionSchemaRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExtractionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExtractionSchemaRequest) ProtoMessage() {}

func (x *CreateExtractionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExtractionSchemaRequest.ProtoReflect.Descriptor instead.
func (*CreateExtractionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{5}
}

func (x *CreateExtractionSchemaRequest) GetSchema() *ExtractionSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type CreateExtractionSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *ExtractionSchema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExtractionSchemaResponse) Reset() {
	*x = CreateExtractionSchemaResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExtractionSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExtractionSchemaResponse) ProtoMessage() {}

func (x *CreateExtractionSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExtractionSchemaResponse.ProtoReflect.Descriptor instead.
func (*CreateExtractionSchemaResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{6}
}

func (x *CreateExtractionSchemaResponse) GetSchema() *ExtractionSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type GetExtractionSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtractionSchemaRequest) Reset() {
	*x = GetExtractionSchemaRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractionSchemaRequest) ProtoMessage() {}

func (x *GetExtractionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractionSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetExtractionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{7}
}

func (x *GetExtractionSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExtractionSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *ExtractionSchema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtractionSchemaResponse) Reset() {
	*x = GetExtractionSchemaResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractionSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractionSchemaResponse) ProtoMessage() {}

func (x *GetExtractionSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractionSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetExtractionSchemaResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{8}
}

func (x *GetExtractionSchemaResponse) GetSchema() *ExtractionSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ListExtractionSchemasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of schemas to return (0 = server default).
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token from a previous ListExtractionSchemasResponse.next_page_token.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExtractionSchemasRequest) Reset() {
	*x = ListExtractionSchemasRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtractionSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtractionSchemasRequest) ProtoMessage() {}

func (x *ListExtractionSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtractionSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListExtractionSchemasRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{9}
}

func (x *ListExtractionSchemasRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExtractionSchemasRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListExtractionSchemasResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Schemas []*ExtractionSchema    `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// Present when further pages are available.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExtractionSchemasResponse) Reset() {
	*x = ListExtractionSchemasResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtractionSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtractionSchemasResponse) ProtoMessage() {}

func (x *ListExtractionSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtractionSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListExtractionSchemasResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{10}
}

func (x *ListExtractionSchemasResponse) GetSchemas() []*ExtractionSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *ListExtractionSchemasResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateExtractionSchemaRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Schema *ExtractionSchema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Fields to update. Omit for a full replacement (not recommended).
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExtractionSchemaRequest) Reset() {
	*x = UpdateExtractionSchemaRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExtractionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExtractionSchemaRequest) ProtoMessage() {}

func (x *UpdateExtractionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExtractionSchemaRequest.ProtoReflect.Descriptor instead.
func (*UpdateExtractionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateExtractionSchemaRequest) GetSchema() *ExtractionSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *UpdateExtractionSchemaRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateExtractionSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *ExtractionSchema      `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExtractionSchemaResponse) Reset() {
	*x = UpdateExtractionSchemaResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExtractionSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExtractionSchemaResponse) ProtoMessage() {}

func (x *UpdateExtractionSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExtractionSchemaResponse.ProtoReflect.Descriptor instead.
func (*UpdateExtractionSchemaResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateExtractionSchemaResponse) GetSchema() *ExtractionSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type DeleteExtractionSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExtractionSchemaRequest) Reset() {
	*x = DeleteExtractionSchemaRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExtractionSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExtractionSchemaRequest) ProtoMessage() {}

func (x *DeleteExtractionSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExtractionSchemaRequest.ProtoReflect.Descriptor instead.
func (*DeleteExtractionSchemaRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteExtractionSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteExtractionSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExtractionSchemaResponse) Reset() {
	*x = DeleteExtractionSchemaResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExtractionSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExtractionSchemaResponse) ProtoMessage() {}

func (x *DeleteExtractionSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExtractionSchemaResponse.ProtoReflect.Descriptor instead.
func (*DeleteExtractionSchemaResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{14}
}

type GetExtractionRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtractionRecordRequest) Reset() {
	*x = GetExtractionRecordRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractionRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractionRecordRequest) ProtoMessage() {}

func (x *GetExtractionRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractionRecordRequest.ProtoReflect.Descriptor instead.
func (*GetExtractionRecordRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{15}
}

func (x *GetExtractionRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExtractionRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExtractionRecord      `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtractionRecordResponse) Reset() {
	*x = GetExtractionRecordResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractionRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractionRecordResponse) ProtoMessage() {}

func (x *GetExtractionRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractionRecordResponse.ProtoReflect.Descriptor instead.
func (*GetExtractionRecordResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{16}
}

func (x *GetExtractionRecordResponse) GetRecord() *ExtractionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListExtractionRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of records to return (0 = server default).
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token from a previous ListExtractionRecordsResponse.next_page_token.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter by schema ID.
	SchemaId string `protobuf:"bytes,3,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// Filter by task ID. At most one record per task exists.
	TaskId        string `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExtractionRecordsRequest) Reset() {
	*x = ListExtractionRecordsRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtractionRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtractionRecordsRequest) ProtoMessage() {}

func (x *ListExtractionRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtractionRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListExtractionRecordsRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{17}
}

func (x *ListExtractionRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExtractionRecordsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListExtractionRecordsRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ListExtractionRecordsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListExtractionRecordsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*ExtractionRecord    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Present when further pages are available.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExtractionRecordsResponse) Reset() {
	*x = ListExtractionRecordsResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtractionRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtractionRecordsResponse) ProtoMessage() {}

func (x *ListExtractionRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtractionRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListExtractionRecordsResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{18}
}

func (x *ListExtractionRecordsResponse) GetRecords() []*ExtractionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListExtractionRecordsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateExtractionRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExtractionRecord      `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExtractionRecordRequest) Reset() {
	*x = CreateExtractionRecordRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExtractionRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExtractionRecordRequest) ProtoMessage() {}

func (x *CreateExtractionRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExtractionRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateExtractionRecordRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{19}
}

func (x *CreateExtractionRecordRequest) GetRecord() *ExtractionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type CreateExtractionRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExtractionRecord      `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExtractionRecordResponse) Reset() {
	*x = CreateExtractionRecordResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExtractionRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExtractionRecordResponse) ProtoMessage() {}

func (x *CreateExtractionRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExtractionRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateExtractionRecordResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{20}
}

func (x *CreateExtractionRecordResponse) GetRecord() *ExtractionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateExtractionRecordRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Record *ExtractionRecord      `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// Fields to update. Omit for a full replacement (not recommended).
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExtractionRecordRequest) Reset() {
	*x = UpdateExtractionRecordRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExtractionRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExtractionRecordRequest) ProtoMessage() {}

func (x *UpdateExtractionRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExtractionRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateExtractionRecordRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateExtractionRecordRequest) GetRecord() *ExtractionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpdateExtractionRecordRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateExtractionRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExtractionRecord      `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExtractionRecordResponse) Reset() {
	*x = UpdateExtractionRecordResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExtractionRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExtractionRecordResponse) ProtoMessage() {}

func (x *UpdateExtractionRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExtractionRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateExtractionRecordResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateExtractionRecordResponse) GetRecord() *ExtractionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type DeleteExtractionRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExtractionRecordRequest) Reset() {
	*x = DeleteExtractionRecordRequest{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExtractionRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExtractionRecordRequest) ProtoMessage() {}

func (x *DeleteExtractionRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExtractionRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteExtractionRecordRequest) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteExtractionRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteExtractionRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExtractionRecordResponse) Reset() {
	*x = DeleteExtractionRecordResponse{}
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExtractionRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExtractionRecordResponse) ProtoMessage() {}

func (x *DeleteExtractionRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integration_browser_v1beta_extraction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExtractionRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteExtractionRecordResponse) Descriptor() ([]byte, []int) {
	return file_integration_browser_v1beta_extraction_proto_rawDescGZIP(), []int{24}
}

var File_integration_browser_v1beta_extraction_proto protoreflect.FileDescriptor

const file_integration_browser_v1beta_extraction_proto_rawDesc = "" +
	"\n" +
	"+integration/browser/v1beta/extraction.proto\x12\x1aintegration.browser.v1beta\x1a\x1bbuf/validate/validate.proto\x1a&dtkt/protoform/v1beta1/protoform.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n" +
	"\bFieldDef\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\x04type\x18\x03 \x01(\tB!\xbaH\x1e\xc8\x01\x01r\x19R\x06stringR\x06numberR\abooleanR\x04type\x12\x1a\n" +
	"\boptional\x18\x04 \x01(\bR\boptional\x120\n" +
	"\adefault\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\adefault\"I\n" +
	"\x0eElementCapture\x12!\n" +
	"\fcss_selector\x18\x01 \x01(\tR\vcssSelector\x12\x14\n" +
	"\x05xpath\x18\x02 \x01(\tR\x05xpath\"\xc8\x02\n" +
	"\x10ExtractionSchema\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\tB\x0e\xe0A\x03\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12F\n" +
	"\x06fields\x18\x04 \x03(\v2$.integration.browser.v1beta.FieldDefB\b\xbaH\x05\x92\x01\x02\b\x01R\x06fields\x12F\n" +
	"\vcreate_time\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampB\t\xe0A\x03\xbaH\x03\xc8\x01\x01R\n" +
	"createTime\x12F\n" +
	"\vupdate_time\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampB\t\xe0A\x03\xbaH\x03\xc8\x01\x01R\n" +
	"updateTime\"\xf8\x04\n" +
	"\x10ExtractionRecord\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\tB\x0e\xe0A\x03\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12(\n" +
	"\tschema_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bschemaId\x12$\n" +
	"\atask_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06taskId\x12P\n" +
	"\x06values\x18\x04 \x03(\v28.integration.browser.v1beta.ExtractionRecord.ValuesEntryR\x06values\x12V\n" +
	"\bcaptures\x18\x05 \x03(\v2:.integration.browser.v1beta.ExtractionRecord.CapturesEntryR\bcaptures\x12F\n" +
	"\vcreate_time\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampB\t\xe0A\x03\xbaH\x03\xc8\x01\x01R\n" +
	"createTime\x12F\n" +
	"\vupdate_time\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampB\t\xe0A\x03\xbaH\x03\xc8\x01\x01R\n" +
	"updateTime\x1aQ\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1ag\n" +
	"\rCapturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.integration.browser.v1beta.ElementCaptureR\x05value:\x028\x01\"\xf0\x01\n" +
	"\x0eExtractionTask\x12\xb3\x01\n" +
	"\tschema_id\x18\x01 \x01(\tB\x95\x01\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\x82\xb5\x18\x85\x01:\x82\x01\n" +
	"Hintegration.browser.v1beta.ExtractionSchemaService.ListExtractionSchemas\x12\x1bthis.schemas.map(i, i.name)\x1a\x19this.schemas.map(i, i.id)R\bschemaId\x12(\n" +
	"\trecord_id\x18\x02 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\brecordId\"m\n" +
	"\x1dCreateExtractionSchemaRequest\x12L\n" +
	"\x06schema\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionSchemaB\x06\xbaH\x03\xc8\x01\x01R\x06schema\"n\n" +
	"\x1eCreateExtractionSchemaResponse\x12L\n" +
	"\x06schema\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionSchemaB\x06\xbaH\x03\xc8\x01\x01R\x06schema\"9\n" +
	"\x1aGetExtractionSchemaRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"k\n" +
	"\x1bGetExtractionSchemaResponse\x12L\n" +
	"\x06schema\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionSchemaB\x06\xbaH\x03\xc8\x01\x01R\x06schema\"c\n" +
	"\x1cListExtractionSchemasRequest\x12$\n" +
	"\tpage_size\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8f\x01\n" +
	"\x1dListExtractionSchemasResponse\x12F\n" +
	"\aschemas\x18\x01 \x03(\v2,.integration.browser.v1beta.ExtractionSchemaR\aschemas\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xaa\x01\n" +
	"\x1dUpdateExtractionSchemaRequest\x12L\n" +
	"\x06schema\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionSchemaB\x06\xbaH\x03\xc8\x01\x01R\x06schema\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"n\n" +
	"\x1eUpdateExtractionSchemaResponse\x12L\n" +
	"\x06schema\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionSchemaB\x06\xbaH\x03\xc8\x01\x01R\x06schema\"<\n" +
	"\x1dDeleteExtractionSchemaRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\" \n" +
	"\x1eDeleteExtractionSchemaResponse\"9\n" +
	"\x1aGetExtractionRecordRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"k\n" +
	"\x1bGetExtractionRecordResponse\x12L\n" +
	"\x06record\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionRecordB\x06\xbaH\x03\xc8\x01\x01R\x06record\"\x99\x01\n" +
	"\x1cListExtractionRecordsRequest\x12$\n" +
	"\tpage_size\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tschema_id\x18\x03 \x01(\tR\bschemaId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\"\x8f\x01\n" +
	"\x1dListExtractionRecordsResponse\x12F\n" +
	"\arecords\x18\x01 \x03(\v2,.integration.browser.v1beta.ExtractionRecordR\arecords\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"m\n" +
	"\x1dCreateExtractionRecordRequest\x12L\n" +
	"\x06record\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionRecordB\x06\xbaH\x03\xc8\x01\x01R\x06record\"n\n" +
	"\x1eCreateExtractionRecordResponse\x12L\n" +
	"\x06record\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionRecordB\x06\xbaH\x03\xc8\x01\x01R\x06record\"\xaa\x01\n" +
	"\x1dUpdateExtractionRecordRequest\x12L\n" +
	"\x06record\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionRecordB\x06\xbaH\x03\xc8\x01\x01R\x06record\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"n\n" +
	"\x1eUpdateExtractionRecordResponse\x12L\n" +
	"\x06record\x18\x01 \x01(\v2,.integration.browser.v1beta.ExtractionRecordB\x06\xbaH\x03\xc8\x01\x01R\x06record\"<\n" +
	"\x1dDeleteExtractionRecordRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\" \n" +
	"\x1eDeleteExtractionRecordResponse2\xe7\x05\n" +
	"\x17ExtractionSchemaService\x12\x8f\x01\n" +
	"\x16CreateExtractionSchema\x129.integration.browser.v1beta.CreateExtractionSchemaRequest\x1a:.integration.browser.v1beta.CreateExtractionSchemaResponse\x12\x86\x01\n" +
	"\x13GetExtractionSchema\x126.integration.browser.v1beta.GetExtractionSchemaRequest\x1a7.integration.browser.v1beta.GetExtractionSchemaResponse\x12\x8c\x01\n" +
	"\x15ListExtractionSchemas\x128.integration.browser.v1beta.ListExtractionSchemasRequest\x1a9.integration.browser.v1beta.ListExtractionSchemasResponse\x12\x8f\x01\n" +
	"\x16UpdateExtractionSchema\x129.integration.browser.v1beta.UpdateExtractionSchemaRequest\x1a:.integration.browser.v1beta.UpdateExtractionSchemaResponse\x12\x8f\x01\n" +
	"\x16DeleteExtractionSchema\x129.integration.browser.v1beta.DeleteExtractionSchemaRequest\x1a:.integration.browser.v1beta.DeleteExtractionSchemaResponse2\xe7\x05\n" +
	"\x17ExtractionRecordService\x12\x86\x01\n" +
	"\x13GetExtractionRecord\x126.integration.browser.v1beta.GetExtractionRecordRequest\x1a7.integration.browser.v1beta.GetExtractionRecordResponse\x12\x8c\x01\n" +
	"\x15ListExtractionRecords\x128.integration.browser.v1beta.ListExtractionRecordsRequest\x1a9.integration.browser.v1beta.ListExtractionRecordsResponse\x12\x8f\x01\n" +
	"\x16CreateExtractionRecord\x129.integration.browser.v1beta.CreateExtractionRecordRequest\x1a:.integration.browser.v1beta.CreateExtractionRecordResponse\x12\x8f\x01\n" +
	"\x16UpdateExtractionRecord\x129.integration.browser.v1beta.UpdateExtractionRecordRequest\x1a:.integration.browser.v1beta.UpdateExtractionRecordResponse\x12\x8f\x01\n" +
	"\x16DeleteExtractionRecord\x129.integration.browser.v1beta.DeleteExtractionRecordRequest\x1a:.integration.browser.v1beta.DeleteExtractionRecordResponseB\xa0\x02\n" +
	"\x1ecom.integration.browser.v1betaB\x0fExtractionProtoP\x01Zcgithub.com/datakit-dev/dtkt-integrations/browser/pkg/proto/integration/browser/v1beta;browserv1beta\xa2\x02\x03IBX\xaa\x02\x1aIntegration.Browser.V1beta\xca\x02\x1aIntegration\\Browser\\V1beta\xe2\x02&Integration\\Browser\\V1beta\\GPBMetadata\xea\x02\x1cIntegration::Browser::V1betab\x06proto3"

var (
	file_integration_browser_v1beta_extraction_proto_rawDescOnce sync.Once
	file_integration_browser_v1beta_extraction_proto_rawDescData []byte
)

func file_integration_browser_v1beta_extraction_proto_rawDescGZIP() []byte {
	file_integration_browser_v1beta_extraction_proto_rawDescOnce.Do(func() {
		file_integration_browser_v1beta_extraction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_browser_v1beta_extraction_proto_rawDesc), len(file_integration_browser_v1beta_extraction_proto_rawDesc)))
	})
	return file_integration_browser_v1beta_extraction_proto_rawDescData
}

var file_integration_browser_v1beta_extraction_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_integration_browser_v1beta_extraction_proto_goTypes = []any{
	(*FieldDef)(nil),                       // 0: integration.browser.v1beta.FieldDef
	(*ElementCapture)(nil),                 // 1: integration.browser.v1beta.ElementCapture
	(*ExtractionSchema)(nil),               // 2: integration.browser.v1beta.ExtractionSchema
	(*ExtractionRecord)(nil),               // 3: integration.browser.v1beta.ExtractionRecord
	(*ExtractionTask)(nil),                 // 4: integration.browser.v1beta.ExtractionTask
	(*CreateExtractionSchemaRequest)(nil),  // 5: integration.browser.v1beta.CreateExtractionSchemaRequest
	(*CreateExtractionSchemaResponse)(nil), // 6: integration.browser.v1beta.CreateExtractionSchemaResponse
	(*GetExtractionSchemaRequest)(nil),     // 7: integration.browser.v1beta.GetExtractionSchemaRequest
	(*GetExtractionSchemaResponse)(nil),    // 8: integration.browser.v1beta.GetExtractionSchemaResponse
	(*ListExtractionSchemasRequest)(nil),   // 9: integration.browser.v1beta.ListExtractionSchemasRequest
	(*ListExtractionSchemasResponse)(nil),  // 10: integration.browser.v1beta.ListExtractionSchemasResponse
	(*UpdateExtractionSchemaRequest)(nil),  // 11: integration.browser.v1beta.UpdateExtractionSchemaRequest
	(*UpdateExtractionSchemaResponse)(nil), // 12: integration.browser.v1beta.UpdateExtractionSchemaResponse
	(*DeleteExtractionSchemaRequest)(nil),  // 13: integration.browser.v1beta.DeleteExtractionSchemaRequest
	(*DeleteExtractionSchemaResponse)(nil), // 14: integration.browser.v1beta.DeleteExtractionSchemaResponse
	(*GetExtractionRecordRequest)(nil),     // 15: integration.browser.v1beta.GetExtractionRecordRequest
	(*GetExtractionRecordResponse)(nil),    // 16: integration.browser.v1beta.GetExtractionRecordResponse
	(*ListExtractionRecordsRequest)(nil),   // 17: integration.browser.v1beta.ListExtractionRecordsRequest
	(*ListExtractionRecordsResponse)(nil),  // 18: integration.browser.v1beta.ListExtractionRecordsResponse
	(*CreateExtractionRecordRequest)(nil),  // 19: integration.browser.v1beta.CreateExtractionRecordRequest
	(*CreateExtractionRecordResponse)(nil), // 20: integration.browser.v1beta.CreateExtractionRecordResponse
	(*UpdateExtractionRecordRequest)(nil),  // 21: integration.browser.v1beta.UpdateExtractionRecordRequest
	(*UpdateExtractionRecordResponse)(nil), // 22: integration.browser.v1beta.UpdateExtractionRecordResponse
	(*DeleteExtractionRecordRequest)(nil),  // 23: integration.browser.v1beta.DeleteExtractionRecordRequest
	(*DeleteExtractionRecordResponse)(nil), // 24: integration.browser.v1beta.DeleteExtractionRecordResponse
	nil,                                    // 25: integration.browser.v1beta.ExtractionRecord.ValuesEntry
	nil,                                    // 26: integration.browser.v1beta.ExtractionRecord.CapturesEntry
	(*structpb.Value)(nil),                 // 27: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),          // 28: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 29: google.protobuf.FieldMask
}
var file_integration_browser_v1beta_extraction_proto_depIdxs = []int32{
	27, // 0: integration.browser.v1beta.FieldDef.default:type_name -> google.protobuf.Value
	0,  // 1: integration.browser.v1beta.ExtractionSchema.fields:type_name -> integration.browser.v1beta.FieldDef
	28, // 2: integration.browser.v1beta.ExtractionSchema.create_time:type_name -> google.protobuf.Timestamp
	28, // 3: integration.browser.v1beta.ExtractionSchema.update_time:type_name -> google.protobuf.Timestamp
	25, // 4: integration.browser.v1beta.ExtractionRecord.values:type_name -> integration.browser.v1beta.ExtractionRecord.ValuesEntry
	26, // 5: integration.browser.v1beta.ExtractionRecord.captures:type_name -> integration.browser.v1beta.ExtractionRecord.CapturesEntry
	28, // 6: integration.browser.v1beta.ExtractionRecord.create_time:type_name -> google.protobuf.Timestamp
	28, // 7: integration.browser.v1beta.ExtractionRecord.update_time:type_name -> google.protobuf.Timestamp
	2,  // 8: integration.browser.v1beta.CreateExtractionSchemaRequest.schema:type_name -> integration.browser.v1beta.ExtractionSchema
	2,  // 9: integration.browser.v1beta.CreateExtractionSchemaResponse.schema:type_name -> integration.browser.v1beta.ExtractionSchema
	2,  // 10: integration.browser.v1beta.GetExtractionSchemaResponse.schema:type_name -> integration.browser.v1beta.ExtractionSchema
	2,  // 11: integration.browser.v1beta.ListExtractionSchemasResponse.schemas:type_name -> integration.browser.v1beta.ExtractionSchema
	2,  // 12: integration.browser.v1beta.UpdateExtractionSchemaRequest.schema:type_name -> integration.browser.v1beta.ExtractionSchema
	29, // 13: integration.browser.v1beta.UpdateExtractionSchemaRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 14: integration.browser.v1beta.UpdateExtractionSchemaResponse.schema:type_name -> integration.browser.v1beta.ExtractionSchema
	3,  // 15: integration.browser.v1beta.GetExtractionRecordResponse.record:type_name -> integration.browser.v1beta.ExtractionRecord
	3,  // 16: integration.browser.v1beta.ListExtractionRecordsResponse.records:type_name -> integration.browser.v1beta.ExtractionRecord
	3,  // 17: integration.browser.v1beta.CreateExtractionRecordRequest.record:type_name -> integration.browser.v1beta.ExtractionRecord
	3,  // 18: integration.browser.v1beta.CreateExtractionRecordResponse.record:type_name -> integration.browser.v1beta.ExtractionRecord
	3,  // 19: integration.browser.v1beta.UpdateExtractionRecordRequest.record:type_name -> integration.browser.v1beta.ExtractionRecord
	29, // 20: integration.browser.v1beta.UpdateExtractionRecordRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 21: integration.browser.v1beta.UpdateExtractionRecordResponse.record:type_name -> integration.browser.v1beta.ExtractionRecord
	27, // 22: integration.browser.v1beta.ExtractionRecord.ValuesEntry.value:type_name -> google.protobuf.Value
	1,  // 23: integration.browser.v1beta.ExtractionRecord.CapturesEntry.value:type_name -> integration.browser.v1beta.ElementCapture
	5,  // 24: integration.browser.v1beta.ExtractionSchemaService.CreateExtractionSchema:input_type -> integration.browser.v1beta.CreateExtractionSchemaRequest
	7,  // 25: integration.browser.v1beta.ExtractionSchemaService.GetExtractionSchema:input_type -> integration.browser.v1beta.GetExtractionSchemaRequest
	9,  // 26: integration.browser.v1beta.ExtractionSchemaService.ListExtractionSchemas:input_type -> integration.browser.v1beta.ListExtractionSchemasRequest
	11, // 27: integration.browser.v1beta.ExtractionSchemaService.UpdateExtractionSchema:input_type -> integration.browser.v1beta.UpdateExtractionSchemaRequest
	13, // 28: integration.browser.v1beta.ExtractionSchemaService.DeleteExtractionSchema:input_type -> integration.browser.v1beta.DeleteExtractionSchemaRequest
	15, // 29: integration.browser.v1beta.ExtractionRecordService.GetExtractionRecord:input_type -> integration.browser.v1beta.GetExtractionRecordRequest
	17, // 30: integration.browser.v1beta.ExtractionRecordService.ListExtractionRecords:input_type -> integration.browser.v1beta.ListExtractionRecordsRequest
	19, // 31: integration.browser.v1beta.ExtractionRecordService.CreateExtractionRecord:input_type -> integration.browser.v1beta.CreateExtractionRecordRequest
	21, // 32: integration.browser.v1beta.ExtractionRecordService.UpdateExtractionRecord:input_type -> integration.browser.v1beta.UpdateExtractionRecordRequest
	23, // 33: integration.browser.v1beta.ExtractionRecordService.DeleteExtractionRecord:input_type -> integration.browser.v1beta.DeleteExtractionRecordRequest
	6,  // 34: integration.browser.v1beta.ExtractionSchemaService.CreateExtractionSchema:output_type -> integration.browser.v1beta.CreateExtractionSchemaResponse
	8,  // 35: integration.browser.v1beta.ExtractionSchemaService.GetExtractionSchema:output_type -> integration.browser.v1beta.GetExtractionSchemaResponse
	10, // 36: integration.browser.v1beta.ExtractionSchemaService.ListExtractionSchemas:output_type -> integration.browser.v1beta.ListExtractionSchemasResponse
	12, // 37: integration.browser.v1beta.ExtractionSchemaService.UpdateExtractionSchema:output_type -> integration.browser.v1beta.UpdateExtractionSchemaResponse
	14, // 38: integration.browser.v1beta.ExtractionSchemaService.DeleteExtractionSchema:output_type -> integration.browser.v1beta.DeleteExtractionSchemaResponse
	16, // 39: integration.browser.v1beta.ExtractionRecordService.GetExtractionRecord:output_type -> integration.browser.v1beta.GetExtractionRecordResponse
	18, // 40: integration.browser.v1beta.ExtractionRecordService.ListExtractionRecords:output_type -> integration.browser.v1beta.ListExtractionRecordsResponse
	20, // 41: integration.browser.v1beta.ExtractionRecordService.CreateExtractionRecord:output_type -> integration.browser.v1beta.CreateExtractionRecordResponse
	22, // 42: integration.browser.v1beta.ExtractionRecordService.UpdateExtractionRecord:output_type -> integration.browser.v1beta.UpdateExtractionRecordResponse
	24, // 43: integration.browser.v1beta.ExtractionRecordService.DeleteExtractionRecord:output_type -> integration.browser.v1beta.DeleteExtractionRecordResponse
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_integration_browser_v1beta_extraction_proto_init() }
func file_integration_browser_v1beta_extraction_proto_init() {
	if File_integration_browser_v1beta_extraction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_browser_v1beta_extraction_proto_rawDesc), len(file_integration_browser_v1beta_extraction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_integration_browser_v1beta_extraction_proto_goTypes,
		DependencyIndexes: file_integration_browser_v1beta_extraction_proto_depIdxs,
		MessageInfos:      file_integration_browser_v1beta_extraction_proto_msgTypes,
	}.Build()
	File_integration_browser_v1beta_extraction_proto = out.File
	file_integration_browser_v1beta_extraction_proto_goTypes = nil
	file_integration_browser_v1beta_extraction_proto_depIdxs = nil
}
